package com.breakinblocks.nutritional.datagen.builtin;

import static com.breakinblocks.nutritional.datagen.builtin.ModCompatFoods.food;
import static com.breakinblocks.nutritional.datagen.builtin.ModCompatFoods.s;

final class CompatWorldMods {

    private CompatWorldMods() {}

    static void register() {
        alexscaves();
        alexsmobs();
        aquaculture();
        brewery();
        eternal_starlight();
        farm_and_charm();
        gobber2();
        minecolonies();
        natures_spirit();
        twilightforest();
        undergarden();
        vinery();
    }

    private static void alexscaves() {
        food("alexscaves:alex_meal", s("fruit", 0.1766f), s("grain", 0.1111f), s("protein", 0.315f), s("vegetable", 0.3972f));
        food("alexscaves:candy_cane", s("fruit", 1.0f));
        food("alexscaves:caramel", s("fruit", 1.0f));
        food("alexscaves:caramel_apple", s("fruit", 1.0f));
        food("alexscaves:cooked_dinosaur_chop", s("protein", 1.0f));
        food("alexscaves:cooked_lanternfish", s("protein", 1.0f));
        food("alexscaves:cooked_mussel", s("protein", 1.0f));
        food("alexscaves:cooked_radgill", s("protein", 1.0f));
        food("alexscaves:cooked_trilocaris_tail", s("protein", 1.0f));
        food("alexscaves:cooked_tripodfish", s("protein", 1.0f));
        food("alexscaves:darkened_apple", s("fruit", 1.0f));
        food("alexscaves:deep_sea_sushi_roll", s("grain", 0.2222f), s("protein", 0.6268f), s("vegetable", 0.151f));
        food("alexscaves:dinosaur_chop", s("protein", 1.0f));
        food("alexscaves:frostmint", s("fruit", 1.0f));
        food("alexscaves:giant_sweetberry", s("fruit", 1.0f));
        food("alexscaves:green_soylent", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("alexscaves:hot_chocolate_bottle", s("fruit", 1.0f));
        food("alexscaves:jelly_bean", s("fruit", 1.0f));
        food("alexscaves:lanternfish", s("protein", 1.0f));
        food("alexscaves:large_peppermint", s("fruit", 1.0f));
        food("alexscaves:peppermint_powder", s("fruit", 1.0f));
        food("alexscaves:pine_nuts", s("protein", 1.0f));
        food("alexscaves:primordial_soup", s("protein", 0.7778f), s("vegetable", 0.2222f));
        food("alexscaves:purple_soda_bottle", s("fruit", 1.0f));
        food("alexscaves:radgill", s("protein", 1.0f));
        food("alexscaves:sea_pig", s("protein", 1.0f));
        food("alexscaves:seething_stew", s("protein", 0.8333f), s("vegetable", 0.1667f));
        food("alexscaves:serene_salad", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("alexscaves:slam", s("fruit", 0.3333f), s("protein", 0.6667f));
        food("alexscaves:small_peppermint", s("fruit", 1.0f));
        food("alexscaves:spelunkie", s("grain", 1.0f));
        food("alexscaves:stinky_fish", s("protein", 1.0f));
        food("alexscaves:sundae", s("dairy", 0.2222f), s("fruit", 0.7778f));
        food("alexscaves:sundrop", s("fruit", 1.0f));
        food("alexscaves:sweet_tooth", s("fruit", 1.0f));
        food("alexscaves:trilocaris_tail", s("protein", 1.0f));
        food("alexscaves:tripodfish", s("protein", 1.0f));
        food("alexscaves:vesper_stew", s("protein", 0.752f), s("vegetable", 0.248f));
        food("alexscaves:vesper_wing", s("protein", 1.0f));
    }

    private static void alexsmobs() {
        food("alexsmobs:banana", s("fruit", 1.0f));
        food("alexsmobs:blobfish", s("protein", 1.0f));
        food("alexsmobs:boiled_emu_egg", s("protein", 1.0f));
        food("alexsmobs:caiman_egg", s("protein", 1.0f));
        food("alexsmobs:cooked_catfish", s("protein", 1.0f));
        food("alexsmobs:cooked_kangaroo_meat", s("protein", 1.0f));
        food("alexsmobs:cooked_lobster_tail", s("protein", 1.0f));
        food("alexsmobs:cooked_moose_ribs", s("protein", 1.0f));
        food("alexsmobs:cosmic_cod", s("protein", 1.0f));
        food("alexsmobs:crocodile_egg", s("protein", 1.0f));
        food("alexsmobs:emu_egg", s("protein", 1.0f));
        food("alexsmobs:flying_fish", s("protein", 1.0f));
        food("alexsmobs:gongylidia", s("vegetable", 1.0f));
        food("alexsmobs:kangaroo_burger", s("grain", 0.5577f), s("protein", 0.4423f));
        food("alexsmobs:kangaroo_meat", s("protein", 1.0f));
        food("alexsmobs:lobster_tail", s("protein", 1.0f));
        food("alexsmobs:mimicream", s("dairy", 1.0f));
        food("alexsmobs:moose_ribs", s("protein", 1.0f));
        food("alexsmobs:mosquito_repellent_stew", s("protein", 0.8333f), s("vegetable", 0.1667f));
        food("alexsmobs:platypus_egg", s("protein", 1.0f));
        food("alexsmobs:rainbow_jelly", s("fruit", 1.0f));
        food("alexsmobs:raw_catfish", s("protein", 1.0f));
        food("alexsmobs:shrimp_fried_rice", s("grain", 0.5f), s("protein", 0.5f));
        food("alexsmobs:terrapin_egg", s("protein", 1.0f));
        food("alexsmobs:triops_eggs", s("protein", 1.0f));
    }

    private static void aquaculture() {
        food("aquaculture:acacia_fish_mount", s("protein", 1.0f));
        food("aquaculture:arapaima", s("protein", 1.0f));
        food("aquaculture:atlantic_cod", s("protein", 1.0f));
        food("aquaculture:atlantic_halibut", s("protein", 1.0f));
        food("aquaculture:atlantic_herring", s("protein", 1.0f));
        food("aquaculture:bayad", s("protein", 1.0f));
        food("aquaculture:birch_fish_mount", s("protein", 1.0f));
        food("aquaculture:blackfish", s("protein", 1.0f));
        food("aquaculture:bluegill", s("protein", 1.0f));
        food("aquaculture:boulti", s("protein", 1.0f));
        food("aquaculture:brown_shrooma", s("protein", 1.0f));
        food("aquaculture:brown_trout", s("protein", 1.0f));
        food("aquaculture:capitaine", s("protein", 1.0f));
        food("aquaculture:carp", s("protein", 1.0f));
        food("aquaculture:catfish", s("protein", 1.0f));
        food("aquaculture:dark_oak_fish_mount", s("protein", 1.0f));
        food("aquaculture:fish_fillet_cooked", s("protein", 1.0f));
        food("aquaculture:fish_fillet_raw", s("protein", 1.0f));
        food("aquaculture:fishing_line", s("protein", 1.0f));
        food("aquaculture:gar", s("protein", 1.0f));
        food("aquaculture:goldfish", s("protein", 1.0f));
        food("aquaculture:jellyfish", s("fruit", 0.5f), s("protein", 0.5f));
        food("aquaculture:jungle_fish_mount", s("protein", 1.0f));
        food("aquaculture:minnow", s("protein", 1.0f));
        food("aquaculture:muskellunge", s("protein", 1.0f));
        food("aquaculture:oak_fish_mount", s("protein", 1.0f));
        food("aquaculture:pacific_halibut", s("protein", 1.0f));
        food("aquaculture:perch", s("protein", 1.0f));
        food("aquaculture:pink_salmon", s("protein", 1.0f));
        food("aquaculture:piranha", s("protein", 1.0f));
        food("aquaculture:pollock", s("protein", 1.0f));
        food("aquaculture:rainbow_trout", s("protein", 1.0f));
        food("aquaculture:red_grouper", s("protein", 1.0f));
        food("aquaculture:red_shrooma", s("protein", 1.0f));
        food("aquaculture:smallmouth_bass", s("protein", 1.0f));
        food("aquaculture:spruce_fish_mount", s("protein", 1.0f));
        food("aquaculture:synodontis", s("protein", 1.0f));
        food("aquaculture:tambaqui", s("protein", 1.0f));
        food("aquaculture:tuna", s("protein", 1.0f));
        food("aquaculture:turtle_soup", s("protein", 0.7778f), s("vegetable", 0.2222f));
    }

    private static void brewery() {
        food("brewery:beer_barley", s("grain", 1.0f));
        food("brewery:beer_haley", s("grain", 1.0f));
        food("brewery:beer_hops", s("grain", 1.0f));
        food("brewery:beer_mug", s("grain", 1.0f));
        food("brewery:beer_nettle", s("grain", 1.0f));
        food("brewery:beer_oat", s("grain", 1.0f));
        food("brewery:beer_wheat", s("grain", 1.0f));
        food("brewery:dark_brew", s("grain", 1.0f));
        food("brewery:dried_barley", s("grain", 1.0f));
        food("brewery:dried_corn", s("grain", 0.3333f), s("vegetable", 0.6667f));
        food("brewery:dried_oat", s("grain", 1.0f));
        food("brewery:dried_wheat", s("grain", 1.0f));
        food("brewery:dumplings", s("grain", 0.3333f), s("vegetable", 0.6667f));
        food("brewery:fried_chicken", s("grain", 0.1137f), s("protein", 0.7169f), s("vegetable", 0.1694f));
        food("brewery:half_chicken", s("protein", 1.0f));
        food("brewery:hops", s("grain", 1.0f));
        food("brewery:mashed_potatoes", s("vegetable", 1.0f));
        food("brewery:pork_knuckle", s("grain", 0.2997f), s("protein", 0.7003f));
        food("brewery:potato_salad", s("vegetable", 1.0f));
        food("brewery:pretzel", s("dairy", 0.1299f), s("grain", 0.7574f), s("protein", 0.1127f));
        food("brewery:sausage", s("protein", 0.7778f), s("vegetable", 0.2222f));
        food("brewery:whiskey_ak", s("grain", 0.8519f), s("vegetable", 0.1481f));
        food("brewery:whiskey_carrasconlabel", s("grain", 0.8519f), s("vegetable", 0.1481f));
        food("brewery:whiskey_cristelwalker", s("grain", 0.7037f), s("vegetable", 0.2963f));
        food("brewery:whiskey_highland_hearth", s("grain", 1.0f));
        food("brewery:whiskey_jamesons_malt", s("fruit", 0.1667f), s("grain", 0.8333f));
        food("brewery:whiskey_jojannik", s("grain", 1.0f));
        food("brewery:whiskey_lilitusinglemalt", s("grain", 1.0f));
        food("brewery:whiskey_maggoallan", s("grain", 1.0f));
        food("brewery:whiskey_smokey_reverie", s("grain", 1.0f));
    }

    private static void eternal_starlight() {
        food("eternal_starlight:abyssal_fruit", s("fruit", 1.0f));
        food("eternal_starlight:aurora_deer_steak", s("protein", 1.0f));
        food("eternal_starlight:bouldershroom_stew", s("protein", 0.5f), s("vegetable", 0.5f));
        food("eternal_starlight:cave_moss", s("vegetable", 1.0f));
        food("eternal_starlight:cooked_aurora_deer_steak", s("protein", 1.0f));
        food("eternal_starlight:cooked_luminaris", s("protein", 1.0f));
        food("eternal_starlight:cooked_luminofish", s("protein", 1.0f));
        food("eternal_starlight:cooked_ratlin_meat", s("protein", 1.0f));
        food("eternal_starlight:cooked_rookfish", s("protein", 1.0f));
        food("eternal_starlight:cooked_shadow_snail_meat", s("protein", 1.0f));
        food("eternal_starlight:crinoa", s("grain", 1.0f));
        food("eternal_starlight:crinoa_ball", s("fruit", 0.2222f), s("grain", 0.7778f));
        food("eternal_starlight:crinoa_porridge", s("grain", 1.0f));
        food("eternal_starlight:doomeden_carrion", s("protein", 1.0f));
        food("eternal_starlight:forgotten_nocturnal_millet", s("grain", 1.0f));
        food("eternal_starlight:jinglestem_crisp", s("vegetable", 1.0f));
        food("eternal_starlight:jinglestem_sandwich", s("grain", 0.3333f), s("vegetable", 0.6667f));
        food("eternal_starlight:luminaris", s("protein", 1.0f));
        food("eternal_starlight:luminofish", s("protein", 1.0f));
        food("eternal_starlight:lunar_berries", s("fruit", 1.0f));
        food("eternal_starlight:lunaris_cactus_fruit", s("fruit", 0.5f), s("vegetable", 0.5f));
        food("eternal_starlight:nocturnal_millet", s("grain", 1.0f));
        food("eternal_starlight:pungency_fruit", s("fruit", 1.0f));
        food("eternal_starlight:pungency_stew", s("fruit", 0.2761f), s("protein", 0.5572f), s("vegetable", 0.1667f));
        food("eternal_starlight:ratlin_meat", s("protein", 1.0f));
        food("eternal_starlight:roasted_forgotten_nocturnal_millet", s("grain", 1.0f));
        food("eternal_starlight:rookfish", s("protein", 1.0f));
        food("eternal_starlight:rotten_flesh_jerky", s("protein", 1.0f));
        food("eternal_starlight:rotten_ham", s("protein", 1.0f));
        food("eternal_starlight:seeker_tentacle", s("protein", 1.0f));
        food("eternal_starlight:shadow_escargot", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("eternal_starlight:shadow_snail_meat", s("protein", 1.0f));
        food("eternal_starlight:shadow_snail_pie", s("grain", 0.5f), s("protein", 0.5f));
        food("eternal_starlight:silver_pungency_fruit", s("fruit", 1.0f));
        food("eternal_starlight:spiral_kelp", s("vegetable", 1.0f));
        food("eternal_starlight:velvetumoss_ball", s("vegetable", 1.0f));
    }

    private static void farm_and_charm() {
        food("farm_and_charm:bacon", s("protein", 1.0f));
        food("farm_and_charm:bacon_with_eggs", s("protein", 1.0f));
        food("farm_and_charm:baked_lamb_ham", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("farm_and_charm:barley", s("grain", 1.0f));
        food("farm_and_charm:barley_patties_with_potatoes", s("grain", 0.4295f), s("protein", 0.1777f), s("vegetable", 0.3928f));
        food("farm_and_charm:barley_soup", s("grain", 0.6349f), s("protein", 0.2698f), s("vegetable", 0.0952f));
        food("farm_and_charm:beef_patty_with_vegetables", s("protein", 0.3785f), s("vegetable", 0.6215f));
        food("farm_and_charm:butter", s("dairy", 0.873f), s("protein", 0.127f));
        food("farm_and_charm:cat_food", s("protein", 1.0f));
        food("farm_and_charm:chicken_parts", s("protein", 1.0f));
        food("farm_and_charm:chicken_wrapped_in_bacon", s("dairy", 0.0976f), s("grain", 0.1612f), s("protein", 0.7412f));
        food("farm_and_charm:cooked_cod", s("dairy", 0.0918f), s("protein", 0.5571f), s("vegetable", 0.3511f));
        food("farm_and_charm:cooked_salmon", s("dairy", 0.1027f), s("protein", 0.6032f), s("vegetable", 0.2941f));
        food("farm_and_charm:corn", s("grain", 0.3333f), s("vegetable", 0.6667f));
        food("farm_and_charm:corn_grits", s("grain", 0.4942f), s("vegetable", 0.5058f));
        food("farm_and_charm:dog_food", s("protein", 0.8931f), s("vegetable", 0.1069f));
        food("farm_and_charm:dough", s("grain", 1.0f));
        food("farm_and_charm:farmer_salad", s("fruit", 0.1694f), s("vegetable", 0.8306f));
        food("farm_and_charm:farmers_bread", s("grain", 1.0f));
        food("farm_and_charm:farmers_breakfast", s("grain", 0.3637f), s("protein", 0.4211f), s("vegetable", 0.2152f));
        food("farm_and_charm:flour", s("grain", 0.8889f), s("vegetable", 0.1111f));
        food("farm_and_charm:goulash", s("protein", 0.2785f), s("vegetable", 0.7215f));
        food("farm_and_charm:grandmothers_strawberry_cake", s("fruit", 0.5184f), s("grain", 0.4816f));
        food("farm_and_charm:lamb_ham", s("protein", 1.0f));
        food("farm_and_charm:lamb_with_corn", s("dairy", 0.0918f), s("grain", 0.1193f), s("protein", 0.3571f), s("vegetable", 0.4318f));
        food("farm_and_charm:lettuce", s("vegetable", 1.0f));
        food("farm_and_charm:minced_beef", s("protein", 1.0f));
        food("farm_and_charm:nettle_tea", s("fruit", 1.0f));
        food("farm_and_charm:nettle_tea_cup", s("fruit", 1.0f));
        food("farm_and_charm:oat", s("grain", 1.0f));
        food("farm_and_charm:oat_pancake", s("fruit", 0.1267f), s("grain", 0.8733f));
        food("farm_and_charm:oatmeal_with_strawberries", s("dairy", 0.2068f), s("fruit", 0.3966f), s("grain", 0.3966f));
        food("farm_and_charm:onion", s("vegetable", 1.0f));
        food("farm_and_charm:onion_soup", s("grain", 0.2252f), s("protein", 0.0825f), s("vegetable", 0.6923f));
        food("farm_and_charm:pasta_with_onion_sauce", s("grain", 0.3898f), s("vegetable", 0.6102f));
        food("farm_and_charm:potato_soup", s("vegetable", 1.0f));
        food("farm_and_charm:potato_with_roast_meat", s("fruit", 0.3152f), s("protein", 0.3895f), s("vegetable", 0.2953f));
        food("farm_and_charm:raw_pasta", s("grain", 1.0f));
        food("farm_and_charm:ribwort_tea", s("fruit", 1.0f));
        food("farm_and_charm:ribwort_tea_cup", s("fruit", 1.0f));
        food("farm_and_charm:roasted_chicken", s("grain", 0.1986f), s("protein", 0.5401f), s("vegetable", 0.2613f));
        food("farm_and_charm:roasted_corn", s("dairy", 0.1293f), s("grain", 0.2593f), s("protein", 0.0929f), s("vegetable", 0.5185f));
        food("farm_and_charm:rotten_tomato", s("vegetable", 1.0f));
        food("farm_and_charm:sausage_with_oat_patty", s("grain", 0.2986f), s("protein", 0.4691f), s("vegetable", 0.2323f));
        food("farm_and_charm:simple_tomato_soup", s("vegetable", 1.0f));
        food("farm_and_charm:strawberry", s("fruit", 1.0f));
        food("farm_and_charm:strawberry_tea", s("fruit", 1.0f));
        food("farm_and_charm:strawberry_tea_cup", s("fruit", 1.0f));
        food("farm_and_charm:stuffed_chicken", s("protein", 0.5443f), s("vegetable", 0.4557f));
        food("farm_and_charm:stuffed_rabbit", s("protein", 0.5746f), s("vegetable", 0.4254f));
        food("farm_and_charm:tomato", s("vegetable", 1.0f));
        food("farm_and_charm:yeast", s("grain", 1.0f));
    }

    private static void gobber2() {
        food("gobber2:gobber2_goo", s("protein", 1.0f));
        food("gobber2:gobber2_goo_nether", s("protein", 1.0f));
        food("gobber2:gobber2_gooey_apple", s("fruit", 1.0f));
        food("gobber2:gobber2_gooey_apple_nether", s("fruit", 1.0f));
        food("gobber2:gobber2_gooey_beef", s("protein", 1.0f));
        food("gobber2:gobber2_gooey_beef_nether", s("protein", 1.0f));
        food("gobber2:gobber2_gooey_beefstew", s("protein", 0.7148f), s("vegetable", 0.2852f));
        food("gobber2:gobber2_gooey_beefstew_nether", s("protein", 0.7148f), s("vegetable", 0.2852f));
        food("gobber2:gobber2_gooey_bread", s("grain", 0.878f), s("protein", 0.122f));
        food("gobber2:gobber2_gooey_bread_nether", s("grain", 0.878f), s("protein", 0.122f));
    }

    private static void minecolonies() {
        food("minecolonies:apple_pie", s("fruit", 0.4902f), s("grain", 0.5098f));
        food("minecolonies:baked_salmon", s("protein", 0.5238f), s("vegetable", 0.4762f));
        food("minecolonies:bell_pepper", s("vegetable", 1.0f));
        food("minecolonies:borscht", s("vegetable", 1.0f));
        food("minecolonies:butter", s("dairy", 1.0f));
        food("minecolonies:butternut_squash", s("vegetable", 1.0f));
        food("minecolonies:cabbage", s("vegetable", 1.0f));
        food("minecolonies:cabochis", s("grain", 0.3333f), s("vegetable", 0.6667f));
        food("minecolonies:cake_batter", s("grain", 1.0f));
        food("minecolonies:cheddar_cheese", s("dairy", 1.0f));
        food("minecolonies:cheese_pizza", s("dairy", 0.2619f), s("grain", 0.4524f), s("vegetable", 0.2857f));
        food("minecolonies:cheese_ravioli", s("dairy", 0.3889f), s("grain", 0.6111f));
        food("minecolonies:chicken_broth", s("protein", 0.5556f), s("vegetable", 0.4444f));
        food("minecolonies:chickpea", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("minecolonies:chorus_bread", s("grain", 1.0f));
        food("minecolonies:congee", s("grain", 0.5556f), s("vegetable", 0.4444f));
        food("minecolonies:cooked_rice", s("grain", 1.0f));
        food("minecolonies:corn", s("grain", 0.3333f), s("vegetable", 0.6667f));
        food("minecolonies:corn_chowder", s("dairy", 0.1667f), s("grain", 0.1389f), s("protein", 0.0833f), s("vegetable", 0.6111f));
        food("minecolonies:cornmeal", s("grain", 0.4444f), s("vegetable", 0.5556f));
        food("minecolonies:creamcheese", s("dairy", 1.0f));
        food("minecolonies:eggdrop_soup", s("protein", 0.4444f), s("vegetable", 0.5556f));
        food("minecolonies:eggplant", s("vegetable", 1.0f));
        food("minecolonies:eggplant_dolma", s("vegetable", 1.0f));
        food("minecolonies:feta_cheese", s("dairy", 1.0f));
        food("minecolonies:fish_dinner", s("protein", 0.8f), s("vegetable", 0.2f));
        food("minecolonies:fish_n_chips", s("grain", 0.1428f), s("protein", 0.302f), s("vegetable", 0.5552f));
        food("minecolonies:flatbread", s("grain", 1.0f));
        food("minecolonies:fried_rice", s("grain", 0.4251f), s("protein", 0.1869f), s("vegetable", 0.3879f));
        food("minecolonies:garlic", s("vegetable", 1.0f));
        food("minecolonies:golden_bread", s("grain", 1.0f));
        food("minecolonies:hand_pie", s("grain", 1.0f));
        food("minecolonies:kebab", s("protein", 0.5556f), s("vegetable", 0.4444f));
        food("minecolonies:kimchi", s("vegetable", 1.0f));
        food("minecolonies:lamb_stew", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("minecolonies:large_milk_bottle", s("dairy", 1.0f));
        food("minecolonies:large_soy_milk_bottle", s("dairy", 1.0f));
        food("minecolonies:lembas_scone", s("grain", 1.0f));
        food("minecolonies:manchet_bread", s("grain", 1.0f));
        food("minecolonies:manchet_dough", s("grain", 1.0f));
        food("minecolonies:meat_ravioli", s("grain", 0.4663f), s("protein", 0.5337f));
        food("minecolonies:milky_bread", s("dairy", 0.5f), s("grain", 0.5f));
        food("minecolonies:mint_jelly", s("fruit", 1.0f));
        food("minecolonies:mint_tea", s("fruit", 1.0f));
        food("minecolonies:mintchoco_cheesecake", s("dairy", 0.6667f), s("grain", 0.3333f));
        food("minecolonies:muffin", s("grain", 1.0f));
        food("minecolonies:muffin_dough", s("grain", 1.0f));
        food("minecolonies:mushroom_pizza", s("dairy", 0.2f), s("grain", 0.4f), s("vegetable", 0.4f));
        food("minecolonies:mutton_dinner", s("protein", 0.5064f), s("vegetable", 0.4936f));
        food("minecolonies:nether_pepper", s("vegetable", 1.0f));
        food("minecolonies:onion", s("vegetable", 1.0f));
        food("minecolonies:pasta_plain", s("dairy", 0.2222f), s("grain", 0.5556f), s("vegetable", 0.2222f));
        food("minecolonies:pasta_tomato", s("grain", 0.3333f), s("vegetable", 0.6667f));
        food("minecolonies:pea_soup", s("dairy", 0.1667f), s("protein", 0.1667f), s("vegetable", 0.6667f));
        food("minecolonies:peas", s("protein", 0.3333f), s("vegetable", 0.6667f));
        food("minecolonies:pepper_hummus", s("protein", 0.3148f), s("vegetable", 0.6852f));
        food("minecolonies:pierogi", s("dairy", 0.1416f), s("grain", 0.475f), s("vegetable", 0.3834f));
        food("minecolonies:pita_hummus", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("minecolonies:plain_cheesecake", s("dairy", 0.5556f), s("grain", 0.2222f), s("protein", 0.2222f));
        food("minecolonies:polenta", s("grain", 0.5185f), s("vegetable", 0.4815f));
        food("minecolonies:potato_soup", s("vegetable", 1.0f));
        food("minecolonies:pottage", s("grain", 0.1352f), s("protein", 0.1111f), s("vegetable", 0.7537f));
        food("minecolonies:ramen", s("grain", 1.0f));
        food("minecolonies:raw_noodle", s("grain", 1.0f));
        food("minecolonies:rice", s("grain", 1.0f));
        food("minecolonies:rice_ball", s("grain", 0.693f), s("protein", 0.1798f), s("vegetable", 0.1272f));
        food("minecolonies:schnitzel", s("grain", 0.3333f), s("protein", 0.6667f));
        food("minecolonies:soybean", s("protein", 1.0f));
        food("minecolonies:spicy_eggplant", s("vegetable", 1.0f));
        food("minecolonies:spicy_grilled_chicken", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("minecolonies:squash_soup", s("vegetable", 1.0f));
        food("minecolonies:steak_dinner", s("protein", 0.8f), s("vegetable", 0.2f));
        food("minecolonies:stew_trencher", s("protein", 0.5f), s("vegetable", 0.5f));
        food("minecolonies:stuffed_pepper", s("vegetable", 1.0f));
        food("minecolonies:stuffed_pita", s("grain", 0.6667f), s("vegetable", 0.3333f));
        food("minecolonies:sugary_bread", s("grain", 1.0f));
        food("minecolonies:sushi_roll", s("grain", 0.6667f), s("protein", 0.3333f));
        food("minecolonies:tacos", s("grain", 1.0f));
        food("minecolonies:tofu", s("protein", 1.0f));
        food("minecolonies:tomato", s("vegetable", 1.0f));
        food("minecolonies:tortillas", s("grain", 0.6296f), s("vegetable", 0.3704f));
        food("minecolonies:veggie_quiche", s("grain", 0.1429f), s("protein", 0.1429f), s("vegetable", 0.7143f));
        food("minecolonies:veggie_ravioli", s("grain", 0.6592f), s("vegetable", 0.3408f));
        food("minecolonies:veggie_soup", s("vegetable", 1.0f));
        food("minecolonies:yogurt", s("dairy", 1.0f));
        food("minecolonies:yogurt_with_berries", s("dairy", 0.3f), s("fruit", 0.7f));
    }

    private static void natures_spirit() {
        food("natures_spirit:coconut", s("fruit", 1.0f));
        food("natures_spirit:coconut_half", s("fruit", 1.0f));
        food("natures_spirit:desert_turnip", s("vegetable", 1.0f));
        food("natures_spirit:green_bearberries", s("fruit", 1.0f));
        food("natures_spirit:half_pizza", s("dairy", 0.3333f), s("grain", 0.6667f));
        food("natures_spirit:purple_bearberries", s("fruit", 1.0f));
        food("natures_spirit:quarter_pizza", s("dairy", 0.3333f), s("grain", 0.6667f));
        food("natures_spirit:red_bearberries", s("fruit", 1.0f));
        food("natures_spirit:shiitake_mushroom", s("vegetable", 1.0f));
        food("natures_spirit:three_quarters_pizza", s("dairy", 0.3333f), s("grain", 0.6667f));
        food("natures_spirit:whole_pizza", s("dairy", 0.1111f), s("grain", 0.6753f), s("vegetable", 0.2136f));
    }

    private static void twilightforest() {
        food("twilightforest:beef_jerky", s("protein", 1.0f));
        food("twilightforest:berry_medley", s("fruit", 1.0f));
        food("twilightforest:blackberry", s("fruit", 1.0f));
        food("twilightforest:blightberry", s("fruit", 1.0f));
        food("twilightforest:blueberry", s("fruit", 1.0f));
        food("twilightforest:chicken_jerky", s("protein", 1.0f));
        food("twilightforest:cicada", s("protein", 1.0f));
        food("twilightforest:cod_jerky", s("protein", 1.0f));
        food("twilightforest:cooked_meef", s("protein", 1.0f));
        food("twilightforest:cooked_venison", s("protein", 1.0f));
        food("twilightforest:duskberry", s("fruit", 1.0f));
        food("twilightforest:experiment_115", s("grain", 1.0f));
        food("twilightforest:fugu_jerky", s("protein", 1.0f));
        food("twilightforest:hydra_chop", s("protein", 1.0f));
        food("twilightforest:maloberry", s("fruit", 1.0f));
        food("twilightforest:mayapple", s("fruit", 1.0f));
        food("twilightforest:maze_wafer", s("dairy", 0.0929f), s("grain", 0.9071f));
        food("twilightforest:meef_jerky", s("protein", 1.0f));
        food("twilightforest:meef_stroganoff", s("fruit", 0.1786f), s("grain", 0.0833f), s("protein", 0.3042f), s("vegetable", 0.4339f));
        food("twilightforest:monster_jerky", s("protein", 1.0f));
        food("twilightforest:moss_soup", s("protein", 0.3333f), s("vegetable", 0.6667f));
        food("twilightforest:mutton_jerky", s("protein", 1.0f));
        food("twilightforest:pork_jerky", s("protein", 1.0f));
        food("twilightforest:rabbit_jerky", s("protein", 1.0f));
        food("twilightforest:raspberry", s("fruit", 1.0f));
        food("twilightforest:raw_meef", s("protein", 1.0f));
        food("twilightforest:raw_venison", s("protein", 1.0f));
        food("twilightforest:salmon_jerky", s("protein", 1.0f));
        food("twilightforest:skyberry", s("fruit", 1.0f));
        food("twilightforest:stale_bread", s("grain", 1.0f));
        food("twilightforest:stingberry", s("fruit", 1.0f));
        food("twilightforest:torchberries", s("fruit", 1.0f));
        food("twilightforest:tropical_fish_jerky", s("protein", 1.0f));
        food("twilightforest:venison_jerky", s("protein", 1.0f));
    }

    private static void undergarden() {
        food("undergarden:blisterberry", s("fruit", 1.0f));
        food("undergarden:blood_globule", s("protein", 1.0f));
        food("undergarden:blood_mushroom", s("vegetable", 1.0f));
        food("undergarden:bloody_stew", s("protein", 0.1667f), s("vegetable", 0.8333f));
        food("undergarden:butterbunch", s("dairy", 0.5f), s("grain", 0.5f));
        food("undergarden:cooked_gwibling", s("protein", 1.0f));
        food("undergarden:droopvine_item", s("fruit", 1.0f));
        food("undergarden:dweller_steak", s("protein", 1.0f));
        food("undergarden:glitterkelp", s("vegetable", 1.0f));
        food("undergarden:gloomgourd_pie", s("grain", 0.5f), s("vegetable", 0.5f));
        food("undergarden:gloomper_leg", s("protein", 1.0f));
        food("undergarden:goo_ball", s("protein", 1.0f));
        food("undergarden:indigo_mushroom", s("vegetable", 1.0f));
        food("undergarden:indigo_stew", s("protein", 0.1667f), s("vegetable", 0.8333f));
        food("undergarden:ink_mushroom", s("vegetable", 1.0f));
        food("undergarden:inky_stew", s("protein", 0.1667f), s("vegetable", 0.8333f));
        food("undergarden:puff_mushroom", s("vegetable", 1.0f));
        food("undergarden:raw_dweller_meat", s("protein", 1.0f));
        food("undergarden:raw_gloomper_leg", s("protein", 1.0f));
        food("undergarden:raw_gwibling", s("protein", 1.0f));
        food("undergarden:roasted_underbeans", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("undergarden:rotten_blisterberry", s("fruit", 1.0f));
        food("undergarden:slop_bowl", s("protein", 0.4669f), s("vegetable", 0.5331f));
        food("undergarden:underbeans", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("undergarden:veil_mushroom", s("vegetable", 1.0f));
        food("undergarden:veiled_stew", s("protein", 0.1667f), s("vegetable", 0.8333f));
    }

    private static void vinery() {
        food("vinery:aegis_wine", s("fruit", 0.3333f), s("vegetable", 0.6667f));
        food("vinery:apple_cider", s("fruit", 1.0f));
        food("vinery:apple_juice", s("fruit", 1.0f));
        food("vinery:apple_wine", s("fruit", 1.0f));
        food("vinery:applesauce", s("fruit", 1.0f));
        food("vinery:bolvar_wine", s("fruit", 1.0f));
        food("vinery:bottle_mojang_noir", s("fruit", 1.0f));
        food("vinery:chenet_wine", s("fruit", 0.756f), s("protein", 0.244f));
        food("vinery:cherry", s("fruit", 1.0f));
        food("vinery:cherry_wine", s("fruit", 1.0f));
        food("vinery:chorus_wine", s("fruit", 1.0f));
        food("vinery:clark_wine", s("fruit", 1.0f));
        food("vinery:creepers_crush", s("fruit", 1.0f));
        food("vinery:cristel_wine", s("fruit", 1.0f));
        food("vinery:eiswein", s("fruit", 1.0f));
        food("vinery:glowing_wine", s("fruit", 1.0f));
        food("vinery:jellie_wine", s("fruit", 1.0f));
        food("vinery:jo_special_mixture", s("fruit", 1.0f));
        food("vinery:jungle_grapes_red", s("fruit", 1.0f));
        food("vinery:jungle_grapes_white", s("fruit", 1.0f));
        food("vinery:jungle_red_grape", s("fruit", 1.0f));
        food("vinery:jungle_white_grape", s("fruit", 1.0f));
        food("vinery:kelp_cider", s("vegetable", 1.0f));
        food("vinery:lilitu_wine", s("fruit", 1.0f));
        food("vinery:magnetic_wine", s("fruit", 1.0f));
        food("vinery:mead", s("fruit", 1.0f));
        food("vinery:mellohi_wine", s("fruit", 1.0f));
        food("vinery:noir_wine", s("fruit", 1.0f));
        food("vinery:red_grape", s("fruit", 1.0f));
        food("vinery:red_grapejuice", s("fruit", 1.0f));
        food("vinery:red_jungle_grapejuice", s("fruit", 1.0f));
        food("vinery:red_savanna_grapejuice", s("fruit", 1.0f));
        food("vinery:red_taiga_grapejuice", s("fruit", 1.0f));
        food("vinery:red_wine", s("fruit", 1.0f));
        food("vinery:rotten_cherry", s("fruit", 1.0f));
        food("vinery:savanna_grapes_red", s("fruit", 1.0f));
        food("vinery:savanna_grapes_white", s("fruit", 1.0f));
        food("vinery:savanna_red_grape", s("fruit", 1.0f));
        food("vinery:savanna_white_grape", s("fruit", 1.0f));
        food("vinery:solaris_wine", s("fruit", 1.0f));
        food("vinery:stal_wine", s("fruit", 1.0f));
        food("vinery:strad_wine", s("fruit", 1.0f));
        food("vinery:taiga_grapes_red", s("fruit", 1.0f));
        food("vinery:taiga_grapes_white", s("fruit", 1.0f));
        food("vinery:taiga_red_grape", s("fruit", 1.0f));
        food("vinery:taiga_white_grape", s("fruit", 1.0f));
        food("vinery:villagers_fright", s("fruit", 1.0f));
        food("vinery:white_grape", s("fruit", 1.0f));
        food("vinery:white_grapejuice", s("fruit", 1.0f));
        food("vinery:white_jungle_grapejuice", s("fruit", 1.0f));
        food("vinery:white_savanna_grapejuice", s("fruit", 1.0f));
        food("vinery:white_taiga_grapejuice", s("fruit", 1.0f));
    }
}
