package com.breakinblocks.nutritional.datagen.builtin;

import static com.breakinblocks.nutritional.datagen.builtin.ModCompatFoods.food;
import static com.breakinblocks.nutritional.datagen.builtin.ModCompatFoods.s;

final class CompatDelightAddons {

    private CompatDelightAddons() {}

    static void register() {
        alexscavesdelight();
        alexsdelight();
        aquaculturedelight();
        casualnessdelight();
        cheesedelight();
        crabbersdelight();
        dungeonsdelight();
        ends_delight();
        eternal_starlight_delight();
        frenchdelight();
        fungidelight();
        gobberdelight();
        minersdelight();
        mynethersdelight();
        natures_delight();
        nydelight();
        oceansdelight();
        ramadandelight();
        rice_delight();
        roll_delight();
        rusticdelight1();
        rusticdelight2();
        twilightdelight();
        undergardendelight();
        vegandelight();
        veggiesdelight();
    }

    private static void alexscavesdelight() {
        food("alexscavesdelight:acid_juice", s("fruit", 1.0f));
        food("alexscavesdelight:acid_pasta", s("grain", 0.8519f), s("protein", 0.1481f));
        food("alexscavesdelight:acid_radgill_stew", s("protein", 0.8333f), s("vegetable", 0.1667f));
        food("alexscavesdelight:bioluminesscence_custard", s("dairy", 0.642f), s("protein", 0.358f));
        food("alexscavesdelight:bioluminesscence_pie", s("grain", 1.0f));
        food("alexscavesdelight:bioluminesscence_pie_slice", s("grain", 1.0f));
        food("alexscavesdelight:caramel_cookie", s("fruit", 0.4444f), s("grain", 0.5556f));
        food("alexscavesdelight:caramel_jem", s("fruit", 1.0f));
        food("alexscavesdelight:caramel_pie", s("fruit", 0.3333f), s("grain", 0.6667f));
        food("alexscavesdelight:caramel_pie_slice", s("fruit", 0.3333f), s("grain", 0.6667f));
        food("alexscavesdelight:chocolate_cookie", s("fruit", 0.5016f), s("grain", 0.4984f));
        food("alexscavesdelight:chocolate_ice_cream", s("dairy", 0.2222f), s("fruit", 0.7778f));
        food("alexscavesdelight:cooked_heart_of_iron", s("protein", 1.0f));
        food("alexscavesdelight:cooked_relicheirus_egg", s("protein", 1.0f));
        food("alexscavesdelight:cooked_tremorsaurus_egg", s("protein", 1.0f));
        food("alexscavesdelight:cooked_tremorzilla_egg", s("protein", 1.0f));
        food("alexscavesdelight:cut_cooked_lanternfish", s("protein", 1.0f));
        food("alexscavesdelight:cut_cooked_radgill", s("protein", 1.0f));
        food("alexscavesdelight:cut_cooked_trilocararis", s("protein", 1.0f));
        food("alexscavesdelight:cut_cooked_tripodfish", s("protein", 1.0f));
        food("alexscavesdelight:cut_dinosaur_chop_cooked", s("protein", 1.0f));
        food("alexscavesdelight:cut_dinosaur_chop_raw", s("protein", 1.0f));
        food("alexscavesdelight:cut_lanternfish", s("protein", 1.0f));
        food("alexscavesdelight:cut_radgill", s("protein", 1.0f));
        food("alexscavesdelight:cut_sea_pig", s("protein", 1.0f));
        food("alexscavesdelight:cut_trilocaris_tail", s("protein", 1.0f));
        food("alexscavesdelight:cut_tripodfish", s("protein", 1.0f));
        food("alexscavesdelight:fiddlehead_roll", s("grain", 0.8259f), s("vegetable", 0.1741f));
        food("alexscavesdelight:fiddlehead_roll_slice", s("grain", 1.0f));
        food("alexscavesdelight:heart_of_iron_humburger", s("grain", 0.405f), s("protein", 0.595f));
        food("alexscavesdelight:honey_glazed_dinosaur_chop", s("fruit", 0.3333f), s("protein", 0.6667f));
        food("alexscavesdelight:lanternfish_roll", s("grain", 0.4199f), s("protein", 0.5801f));
        food("alexscavesdelight:lanternfish_soup", s("protein", 0.4984f), s("vegetable", 0.5016f));
        food("alexscavesdelight:licoroot_juice", s("fruit", 1.0f));
        food("alexscavesdelight:licoroot_roll", s("grain", 0.8259f), s("vegetable", 0.1741f));
        food("alexscavesdelight:licoroot_roll_slice", s("grain", 1.0f));
        food("alexscavesdelight:meat_pie", s("grain", 0.5f), s("protein", 0.5f));
        food("alexscavesdelight:meat_pie_slice", s("grain", 0.5f), s("protein", 0.5f));
        food("alexscavesdelight:mix_gelatin_pumpkin", s("vegetable", 1.0f));
        food("alexscavesdelight:mussel_soup", s("protein", 0.4984f), s("vegetable", 0.5016f));
        food("alexscavesdelight:pewen_sap_dough", s("grain", 0.8816f), s("protein", 0.1184f));
        food("alexscavesdelight:pewen_shake", s("dairy", 1.0f));
        food("alexscavesdelight:pine_nuts_cookie", s("grain", 0.5f), s("protein", 0.5f));
        food("alexscavesdelight:primal_noodle_soup", s("grain", 0.1905f), s("protein", 0.6046f), s("vegetable", 0.2049f));
        food("alexscavesdelight:pure_darkness_pie", s("grain", 1.0f));
        food("alexscavesdelight:pure_darkness_pie_slice", s("grain", 1.0f));
        food("alexscavesdelight:pure_darkness_shake", s("dairy", 1.0f));
        food("alexscavesdelight:radgill_roll", s("grain", 0.5865f), s("protein", 0.4135f));
        food("alexscavesdelight:relicheirus_noodle_soup", s("grain", 0.1905f), s("protein", 0.5918f), s("vegetable", 0.2178f));
        food("alexscavesdelight:sea_pig_soup", s("protein", 0.3333f), s("vegetable", 0.6667f));
        food("alexscavesdelight:spelunkie_shake", s("dairy", 0.5075f), s("grain", 0.4925f));
        food("alexscavesdelight:sulfur_cookie", s("grain", 1.0f));
        food("alexscavesdelight:sulfur_shake", s("dairy", 1.0f));
        food("alexscavesdelight:sweetberry_ice_cream", s("dairy", 0.5f), s("fruit", 0.5f));
        food("alexscavesdelight:tectonic_roll", s("grain", 1.0f));
        food("alexscavesdelight:toxic_hamburger", s("grain", 0.3333f), s("protein", 0.6667f));
        food("alexscavesdelight:toxic_noodle_soup", s("grain", 0.2642f), s("protein", 0.5794f), s("vegetable", 0.1564f));
        food("alexscavesdelight:toxic_pie", s("grain", 1.0f));
        food("alexscavesdelight:toxic_pie_slice", s("grain", 1.0f));
        food("alexscavesdelight:tree_star_juice", s("fruit", 1.0f));
        food("alexscavesdelight:tremorzilla_maet", s("protein", 1.0f));
        food("alexscavesdelight:trilocararis_roll", s("grain", 0.5865f), s("protein", 0.4135f));
        food("alexscavesdelight:tripodfish_roll", s("grain", 0.4199f), s("protein", 0.5801f));
        food("alexscavesdelight:tripodfish_soup", s("protein", 0.4984f), s("vegetable", 0.5016f));
        food("alexscavesdelight:uranium_pie", s("grain", 1.0f));
        food("alexscavesdelight:uranium_pie_slice", s("grain", 1.0f));
        food("alexscavesdelight:vanilla_ice_cream", s("dairy", 1.0f));
    }

    private static void alexsdelight() {
        food("alexsdelight:acacia_blossom_soup", s("grain", 0.1403f), s("protein", 0.3315f), s("vegetable", 0.5282f));
        food("alexsdelight:bison_burger", s("grain", 0.2368f), s("protein", 0.4291f), s("vegetable", 0.3341f));
        food("alexsdelight:bison_patty", s("protein", 1.0f));
        food("alexsdelight:bunfungus_sandwich", s("grain", 0.6012f), s("vegetable", 0.3988f));
        food("alexsdelight:cooked_bison", s("protein", 1.0f));
        food("alexsdelight:cooked_bunfungus", s("grain", 0.5f), s("vegetable", 0.5f));
        food("alexsdelight:cooked_bunfungus_drumstick", s("grain", 0.3333f), s("protein", 0.3333f), s("vegetable", 0.3333f));
        food("alexsdelight:cooked_catfish_slice", s("protein", 1.0f));
        food("alexsdelight:cooked_centipede_leg", s("protein", 1.0f));
        food("alexsdelight:cooked_kangaroo_shank", s("protein", 1.0f));
        food("alexsdelight:cooked_loose_moose_rib", s("protein", 1.0f));
        food("alexsdelight:kangaroo_pasta", s("grain", 0.4105f), s("protein", 0.3386f), s("vegetable", 0.2509f));
        food("alexsdelight:kangaroo_stew", s("protein", 0.4253f), s("vegetable", 0.5747f));
        food("alexsdelight:lobster_pasta", s("grain", 0.2487f), s("protein", 0.4844f), s("vegetable", 0.2669f));
        food("alexsdelight:maggot_salad", s("vegetable", 1.0f));
        food("alexsdelight:raw_bunfungus", s("grain", 0.5f), s("vegetable", 0.5f));
        food("alexsdelight:raw_bunfungus_drumstick", s("grain", 0.3333f), s("protein", 0.3333f), s("vegetable", 0.3333f));
        food("alexsdelight:raw_catfish_slice", s("protein", 1.0f));
    }

    private static void aquaculturedelight() {
        food("aquaculturedelight:baked_pollock_with_carrots", s("protein", 0.2067f), s("vegetable", 0.7933f));
        food("aquaculturedelight:bass_stew", s("protein", 0.408f), s("vegetable", 0.592f));
        food("aquaculturedelight:buckling", s("protein", 0.7778f), s("vegetable", 0.2222f));
        food("aquaculturedelight:catfish_barbecue", s("protein", 0.5556f), s("vegetable", 0.4444f));
        food("aquaculturedelight:cooked_small_turtle_meat", s("protein", 1.0f));
        food("aquaculturedelight:crispy_fried_perch", s("grain", 0.2222f), s("protein", 0.7778f));
        food("aquaculturedelight:crispy_nori_kelp", s("vegetable", 1.0f));
        food("aquaculturedelight:fish_and_chips", s("protein", 0.3079f), s("vegetable", 0.6921f));
        food("aquaculturedelight:fish_chorba", s("protein", 0.4734f), s("vegetable", 0.5266f));
        food("aquaculturedelight:fish_roll_medley", s("grain", 0.3335f), s("protein", 0.6665f));
        food("aquaculturedelight:fish_roll_medley_1", s("grain", 0.5f), s("protein", 0.5f));
        food("aquaculturedelight:fish_roll_medley_2", s("grain", 0.5f), s("protein", 0.5f));
        food("aquaculturedelight:fish_roll_medley_3", s("grain", 0.5f), s("protein", 0.5f));
        food("aquaculturedelight:fish_roll_medley_4", s("grain", 0.5f), s("protein", 0.5f));
        food("aquaculturedelight:fish_roll_medley_5", s("grain", 0.5f), s("protein", 0.5f));
        food("aquaculturedelight:fish_roll_medley_6", s("grain", 0.5f), s("protein", 0.5f));
        food("aquaculturedelight:fish_roll_medley_7", s("grain", 0.5f), s("protein", 0.5f));
        food("aquaculturedelight:fried_perch_roll", s("grain", 0.5555f), s("protein", 0.4445f));
        food("aquaculturedelight:halaszle", s("grain", 0.2552f), s("protein", 0.4395f), s("vegetable", 0.3053f));
        food("aquaculturedelight:halibut_with_tartar_sauce", s("protein", 0.6643f), s("vegetable", 0.3357f));
        food("aquaculturedelight:jellyfish_jelly", s("fruit", 0.3333f), s("grain", 0.3333f), s("protein", 0.3333f));
        food("aquaculturedelight:large_fish_with_vegetables", s("grain", 0.2033f), s("protein", 0.4014f), s("vegetable", 0.3954f));
        food("aquaculturedelight:poor_fisher_chowder", s("protein", 0.8f), s("vegetable", 0.2f));
        food("aquaculturedelight:raw_fish_fillet_roll", s("grain", 0.4761f), s("protein", 0.5239f));
        food("aquaculturedelight:rollmops", s("grain", 0.3333f), s("protein", 0.2201f), s("vegetable", 0.4466f));
        food("aquaculturedelight:small_turtle_meat", s("protein", 1.0f));
        food("aquaculturedelight:tuna_spaghetti", s("grain", 0.2925f), s("protein", 0.4406f), s("vegetable", 0.2669f));
        food("aquaculturedelight:turtle_meat_dish", s("protein", 0.578f), s("vegetable", 0.422f));
        food("aquaculturedelight:unusual_fish_soup", s("grain", 0.2067f), s("protein", 0.429f), s("vegetable", 0.3643f));
    }

    private static void casualnessdelight() {
        food("casualnessdelight:beef_bobo_chicken", s("protein", 1.0f));
        food("casualnessdelight:beef_noodles", s("grain", 0.2438f), s("protein", 0.5052f), s("vegetable", 0.2509f));
        food("casualnessdelight:bobo_chicken", s("protein", 0.7037f), s("vegetable", 0.2963f));
        food("casualnessdelight:bowl_of_paper_wrapped_fish", s("protein", 1.0f));
        food("casualnessdelight:bowl_of_sweet_rice", s("grain", 1.0f));
        food("casualnessdelight:cabbage_bobo_chicken", s("protein", 0.5f), s("vegetable", 0.5f));
        food("casualnessdelight:capsicum_sauce", s("vegetable", 1.0f));
        food("casualnessdelight:cheese_wheel", s("dairy", 1.0f));
        food("casualnessdelight:cheese_wheel_slice", s("dairy", 1.0f));
        food("casualnessdelight:chicken_bobo_chicken", s("protein", 1.0f));
        food("casualnessdelight:cooked_donkey_meat", s("protein", 1.0f));
        food("casualnessdelight:donkey_burger", s("grain", 0.2418f), s("protein", 0.4921f), s("vegetable", 0.2661f));
        food("casualnessdelight:fish_and_chips", s("grain", 0.1679f), s("protein", 0.4132f), s("vegetable", 0.4189f));
        food("casualnessdelight:fried_cake", s("grain", 0.7381f), s("protein", 0.1579f), s("vegetable", 0.104f));
        food("casualnessdelight:fried_chicken_chip", s("protein", 1.0f));
        food("casualnessdelight:fried_fish", s("protein", 1.0f));
        food("casualnessdelight:fried_mushroom", s("protein", 0.4444f), s("vegetable", 0.5556f));
        food("casualnessdelight:fried_strange_mushroom", s("vegetable", 1.0f));
        food("casualnessdelight:paper_wrapped_fish", s("protein", 0.3333f), s("vegetable", 0.6667f));
        food("casualnessdelight:phantom_dumplings", s("grain", 0.3333f), s("protein", 0.2461f), s("vegetable", 0.4206f));
        food("casualnessdelight:phantom_puff", s("dairy", 0.5763f), s("protein", 0.4237f));
        food("casualnessdelight:potato_bobo_chicken", s("protein", 0.5f), s("vegetable", 0.5f));
        food("casualnessdelight:potato_chip", s("vegetable", 1.0f));
        food("casualnessdelight:potato_slice", s("vegetable", 1.0f));
        food("casualnessdelight:raw_cabbage_bobo_chicken", s("protein", 0.1667f), s("vegetable", 0.8333f));
        food("casualnessdelight:raw_cheese_wheel", s("dairy", 0.53f), s("protein", 0.1494f), s("vegetable", 0.3205f));
        food("casualnessdelight:raw_chicken_bobo_chicken", s("protein", 1.0f));
        food("casualnessdelight:raw_donkey_meat", s("protein", 1.0f));
        food("casualnessdelight:raw_fried_dumpling", s("grain", 1.0f));
        food("casualnessdelight:raw_glue_pudding", s("dairy", 0.6667f), s("grain", 0.3333f));
        food("casualnessdelight:raw_potato_bobo_chicken", s("protein", 0.5f), s("vegetable", 0.5f));
        food("casualnessdelight:raw_spring_roll", s("grain", 0.4902f), s("protein", 0.3004f), s("vegetable", 0.2094f));
        food("casualnessdelight:roast_gluten", s("grain", 0.3333f), s("protein", 0.6667f));
        food("casualnessdelight:spicy_strips", s("protein", 0.7396f), s("vegetable", 0.2604f));
        food("casualnessdelight:spring_roll", s("grain", 0.6601f), s("protein", 0.2003f), s("vegetable", 0.1396f));
        food("casualnessdelight:spring_roll_medley", s("grain", 0.7734f), s("protein", 0.1335f), s("vegetable", 0.0931f));
        food("casualnessdelight:stargazy_pie", s("grain", 1.0f));
        food("casualnessdelight:stargazy_pie_slice", s("grain", 1.0f));
        food("casualnessdelight:sweet_rice", s("fruit", 0.3583f), s("grain", 0.5611f), s("vegetable", 0.0805f));
        food("casualnessdelight:tonkatsu", s("grain", 0.1111f), s("protein", 0.8889f));
        food("casualnessdelight:yorkshire_pudding", s("dairy", 0.3117f), s("grain", 0.2096f), s("protein", 0.4787f));
    }

    private static void cheesedelight() {
        food("cheesedelight:cheese", s("dairy", 1.0f));
        food("cheesedelight:cheese_rotten_1", s("dairy", 1.0f));
        food("cheesedelight:cheese_rotten_2", s("dairy", 1.0f));
        food("cheesedelight:cheese_sandwich", s("dairy", 0.479f), s("grain", 0.521f));
        food("cheesedelight:cheeseburger", s("dairy", 0.0833f), s("grain", 0.3936f), s("protein", 0.5231f));
        food("cheesedelight:grilled_cheese_sandwich", s("dairy", 0.486f), s("grain", 0.514f));
        food("cheesedelight:pizza", s("dairy", 0.1175f), s("grain", 0.6646f), s("vegetable", 0.2179f));
        food("cheesedelight:pizza_slice", s("dairy", 0.3333f), s("grain", 0.6667f));
    }

    private static void crabbersdelight() {
        food("crabbersdelight:bisque", s("dairy", 0.0875f), s("grain", 0.1732f), s("protein", 0.2361f), s("vegetable", 0.5033f));
        food("crabbersdelight:clam", s("protein", 1.0f));
        food("crabbersdelight:clam_bake", s("protein", 0.7798f), s("vegetable", 0.2202f));
        food("crabbersdelight:clam_chowder", s("dairy", 0.0899f), s("protein", 0.5354f), s("vegetable", 0.3747f));
        food("crabbersdelight:clawster", s("protein", 1.0f));
        food("crabbersdelight:coconut", s("fruit", 1.0f));
        food("crabbersdelight:coconut_halve", s("fruit", 1.0f));
        food("crabbersdelight:coconut_milk", s("dairy", 0.1667f), s("fruit", 0.8333f));
        food("crabbersdelight:coconut_pudding", s("dairy", 0.174f), s("fruit", 0.5622f), s("protein", 0.2639f));
        food("crabbersdelight:cooked_clam_meat", s("protein", 1.0f));
        food("crabbersdelight:cooked_clawster", s("protein", 1.0f));
        food("crabbersdelight:cooked_crab", s("protein", 1.0f));
        food("crabbersdelight:cooked_frog_leg", s("protein", 1.0f));
        food("crabbersdelight:cooked_glow_squid_tentacles", s("protein", 1.0f));
        food("crabbersdelight:cooked_pufferfish_slice", s("protein", 1.0f));
        food("crabbersdelight:cooked_shrimp", s("protein", 1.0f));
        food("crabbersdelight:cooked_squid_tentacles", s("protein", 1.0f));
        food("crabbersdelight:cooked_tropical_fish", s("protein", 1.0f));
        food("crabbersdelight:cooked_tropical_fish_slice", s("protein", 1.0f));
        food("crabbersdelight:crab", s("protein", 1.0f));
        food("crabbersdelight:crab_cakes", s("grain", 0.1278f), s("protein", 0.7167f), s("vegetable", 0.1554f));
        food("crabbersdelight:crab_legs", s("protein", 1.0f));
        food("crabbersdelight:jar_of_pickles", s("vegetable", 1.0f));
        food("crabbersdelight:kelp_shake", s("dairy", 0.1111f), s("vegetable", 0.8889f));
        food("crabbersdelight:pufferfish_slice", s("protein", 1.0f));
        food("crabbersdelight:raw_clam_meat", s("protein", 1.0f));
        food("crabbersdelight:raw_glow_squid_tentacles", s("protein", 1.0f));
        food("crabbersdelight:raw_squid_tentacles", s("protein", 1.0f));
        food("crabbersdelight:sea_pickle_juice", s("vegetable", 1.0f));
        food("crabbersdelight:seafood_gumbo", s("grain", 0.1276f), s("protein", 0.6781f), s("vegetable", 0.1943f));
        food("crabbersdelight:shrimp", s("protein", 1.0f));
        food("crabbersdelight:shrimp_fried_rice", s("grain", 0.3996f), s("protein", 0.3012f), s("vegetable", 0.2992f));
        food("crabbersdelight:shrimp_skewer", s("protein", 0.7896f), s("vegetable", 0.2104f));
        food("crabbersdelight:squid_kebab", s("protein", 0.5648f), s("vegetable", 0.4352f));
        food("crabbersdelight:stuffed_nautilus_shell", s("protein", 0.4601f), s("vegetable", 0.5399f));
        food("crabbersdelight:tropical_fish_slice", s("protein", 1.0f));
    }

    private static void dungeonsdelight() {
        food("dungeonsdelight:amber_e_olio", s("grain", 0.2222f), s("protein", 0.6667f), s("vegetable", 0.1111f));
        food("dungeonsdelight:ancient_egg", s("protein", 1.0f));
        food("dungeonsdelight:arcane_chili", s("protein", 0.3333f), s("vegetable", 0.6667f));
        food("dungeonsdelight:au_rotten_potatoes", s("dairy", 0.2794f), s("fruit", 0.2231f), s("grain", 0.1642f), s("vegetable", 0.3333f));
        food("dungeonsdelight:aurora_ice_cream", s("dairy", 0.7531f), s("protein", 0.2469f));
        food("dungeonsdelight:blazing_blood_sausage", s("grain", 0.6667f), s("protein", 0.3333f));
        food("dungeonsdelight:bloated_baked_potato", s("dairy", 0.1325f), s("fruit", 0.1121f), s("grain", 0.1223f), s("protein", 0.2997f), s("vegetable", 0.3333f));
        food("dungeonsdelight:bloody_mary", s("protein", 0.5f), s("vegetable", 0.5f));
        food("dungeonsdelight:bogged_brain", s("protein", 1.0f));
        food("dungeonsdelight:breeze_cream_cone", s("dairy", 0.3333f), s("protein", 0.3333f), s("vegetable", 0.3333f));
        food("dungeonsdelight:brined_flesh", s("protein", 1.0f));
        food("dungeonsdelight:bubblegunk", s("fruit", 1.0f));
        food("dungeonsdelight:bug_chops", s("protein", 1.0f));
        food("dungeonsdelight:candied_silverfish_sucker", s("protein", 1.0f));
        food("dungeonsdelight:candied_vex_sucker", s("fruit", 1.0f));
        food("dungeonsdelight:chicken_jockey_sandwich", s("grain", 0.1667f), s("protein", 0.5728f), s("vegetable", 0.2605f));
        food("dungeonsdelight:chloropasta", s("grain", 0.3333f), s("protein", 0.6667f));
        food("dungeonsdelight:cleaved_ancient_egg", s("protein", 1.0f));
        food("dungeonsdelight:cob_n_candy", s("fruit", 1.0f));
        food("dungeonsdelight:cooked_marbled_meat", s("protein", 1.0f));
        food("dungeonsdelight:cooked_sniffer_shank", s("protein", 1.0f));
        food("dungeonsdelight:cooked_snifferwurst", s("protein", 0.8159f), s("vegetable", 0.1841f));
        food("dungeonsdelight:croak_monster", s("protein", 1.0f));
        food("dungeonsdelight:devilish_eggs", s("protein", 1.0f));
        food("dungeonsdelight:fluffy_floss", s("fruit", 0.3333f), s("protein", 0.6667f));
        food("dungeonsdelight:fried_bug_chops", s("protein", 1.0f));
        food("dungeonsdelight:fried_ghast_calamari", s("protein", 1.0f));
        food("dungeonsdelight:gelled_salad", s("vegetable", 1.0f));
        food("dungeonsdelight:ghast_calamari", s("protein", 1.0f));
        food("dungeonsdelight:ghast_roll", s("grain", 0.5328f), s("protein", 0.223f), s("vegetable", 0.2443f));
        food("dungeonsdelight:ghast_tentacle", s("protein", 1.0f));
        food("dungeonsdelight:ghastly_spirits", s("fruit", 0.206f), s("grain", 0.3333f), s("protein", 0.4607f));
        food("dungeonsdelight:ghoulash", s("protein", 0.5186f), s("vegetable", 0.4814f));
        food("dungeonsdelight:gritty_flesh", s("protein", 1.0f));
        food("dungeonsdelight:guardian_angel", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("dungeonsdelight:gyudon", s("grain", 0.6094f), s("protein", 0.2762f), s("vegetable", 0.1144f));
        food("dungeonsdelight:haggis", s("grain", 0.1111f), s("protein", 0.8889f));
        food("dungeonsdelight:hydra_fricassee", s("dairy", 0.1315f), s("protein", 0.8685f));
        food("dungeonsdelight:jelly_beans", s("fruit", 0.2299f), s("protein", 0.5977f), s("vegetable", 0.1724f));
        food("dungeonsdelight:liveroot_beer", s("dairy", 0.2003f), s("fruit", 0.3485f), s("grain", 0.3333f), s("protein", 0.1178f));
        food("dungeonsdelight:lutefisk", s("protein", 1.0f));
        food("dungeonsdelight:malicious_sandwich", s("grain", 0.4314f), s("protein", 0.5686f));
        food("dungeonsdelight:marbled_meat", s("protein", 1.0f));
        food("dungeonsdelight:marshbellow", s("fruit", 1.0f));
        food("dungeonsdelight:maze_roll", s("fruit", 0.3021f), s("grain", 0.4844f), s("protein", 0.2136f));
        food("dungeonsdelight:maze_smore", s("fruit", 0.1184f), s("grain", 0.8816f));
        food("dungeonsdelight:meef_wellington", s("grain", 0.1111f), s("protein", 0.5821f), s("vegetable", 0.3068f));
        food("dungeonsdelight:monster_burger", s("fruit", 0.0949f), s("grain", 0.2125f), s("protein", 0.5231f), s("vegetable", 0.1695f));
        food("dungeonsdelight:monster_cake", s("grain", 1.0f));
        food("dungeonsdelight:monster_cake_slice", s("grain", 1.0f));
        food("dungeonsdelight:monster_muffin", s("grain", 0.3333f), s("protein", 0.6667f));
        food("dungeonsdelight:necronog", s("dairy", 0.3397f), s("fruit", 0.0839f), s("protein", 0.5763f));
        food("dungeonsdelight:ossobuco", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("dungeonsdelight:poi", s("vegetable", 1.0f));
        food("dungeonsdelight:poi_cup", s("vegetable", 1.0f));
        food("dungeonsdelight:poisonous_poutine", s("dairy", 0.2436f), s("fruit", 0.1121f), s("grain", 0.1223f), s("protein", 0.2997f), s("vegetable", 0.2222f));
        food("dungeonsdelight:polterghast_pizza", s("dairy", 0.2896f), s("grain", 0.2369f), s("protein", 0.1874f), s("vegetable", 0.2861f));
        food("dungeonsdelight:polterghast_pizza_slice", s("dairy", 0.3333f), s("grain", 0.6667f));
        food("dungeonsdelight:putrid_spice_latte", s("dairy", 0.514f), s("fruit", 0.1106f), s("vegetable", 0.3754f));
        food("dungeonsdelight:rancid_reduction", s("dairy", 0.1611f), s("fruit", 0.1151f), s("protein", 0.3333f), s("vegetable", 0.3905f));
        food("dungeonsdelight:rot_roast", s("fruit", 0.2166f), s("protein", 0.5757f), s("vegetable", 0.2077f));
        food("dungeonsdelight:rotgourd_slice", s("vegetable", 1.0f));
        food("dungeonsdelight:rotpop", s("fruit", 0.3333f), s("vegetable", 0.6667f));
        food("dungeonsdelight:rotten_tripe", s("protein", 1.0f));
        food("dungeonsdelight:rubaboo", s("fruit", 0.2222f), s("protein", 0.6111f), s("vegetable", 0.1667f));
        food("dungeonsdelight:rubaboo_cup", s("fruit", 0.2222f), s("protein", 0.6111f), s("vegetable", 0.1667f));
        food("dungeonsdelight:salt_soaked_stew", s("protein", 0.7062f), s("vegetable", 0.2938f));
        food("dungeonsdelight:salt_soaked_stew_cup", s("protein", 0.7062f), s("vegetable", 0.2938f));
        food("dungeonsdelight:scaly_fiddlehead_risotto", s("grain", 1.0f));
        food("dungeonsdelight:sculk_apple", s("fruit", 1.0f));
        food("dungeonsdelight:sculk_catblueberry", s("fruit", 1.0f));
        food("dungeonsdelight:sculk_dogapple", s("fruit", 1.0f));
        food("dungeonsdelight:sculk_mayo", s("protein", 1.0f));
        food("dungeonsdelight:sculk_tart", s("grain", 1.0f));
        food("dungeonsdelight:sculk_tart_slice", s("grain", 1.0f));
        food("dungeonsdelight:shiokara", s("protein", 1.0f));
        food("dungeonsdelight:silverfish_abdomen", s("protein", 1.0f));
        food("dungeonsdelight:silverfish_and_chips", s("protein", 0.5f), s("vegetable", 0.5f));
        food("dungeonsdelight:silverfish_fried_rice", s("grain", 0.2864f), s("protein", 0.4471f), s("vegetable", 0.2664f));
        food("dungeonsdelight:sinigang", s("grain", 0.2222f), s("protein", 0.6111f), s("vegetable", 0.1667f));
        food("dungeonsdelight:skyberry_brew", s("fruit", 1.0f));
        food("dungeonsdelight:smoked_spider_meat", s("protein", 1.0f));
        food("dungeonsdelight:sniffer_shank", s("protein", 1.0f));
        food("dungeonsdelight:snifferwurst", s("protein", 0.7239f), s("vegetable", 0.2761f));
        food("dungeonsdelight:snuffledog", s("grain", 0.1111f), s("protein", 0.5649f), s("vegetable", 0.324f));
        food("dungeonsdelight:soaked_skewer", s("protein", 0.6095f), s("vegetable", 0.3905f));
        food("dungeonsdelight:soft_serve_sniffer_egg", s("protein", 1.0f));
        food("dungeonsdelight:spider_bisque", s("protein", 0.6956f), s("vegetable", 0.3044f));
        food("dungeonsdelight:spider_bubble_tea", s("fruit", 0.3333f), s("protein", 0.6667f));
        food("dungeonsdelight:spider_donut", s("grain", 0.3333f), s("protein", 0.6667f));
        food("dungeonsdelight:spider_extract", s("protein", 1.0f));
        food("dungeonsdelight:spider_meat", s("protein", 1.0f));
        food("dungeonsdelight:spider_pie", s("grain", 1.0f));
        food("dungeonsdelight:spider_pie_slice", s("grain", 1.0f));
        food("dungeonsdelight:spider_salmagundi", s("protein", 0.6111f), s("vegetable", 0.3889f));
        food("dungeonsdelight:spider_salmagundi_cup", s("protein", 0.6111f), s("vegetable", 0.3889f));
        food("dungeonsdelight:spider_tanghulu", s("fruit", 0.2222f), s("protein", 0.6506f), s("vegetable", 0.1272f));
        food("dungeonsdelight:sweetbread", s("grain", 0.6075f), s("protein", 0.3925f));
        food("dungeonsdelight:takoyaki", s("grain", 0.1111f), s("protein", 0.693f), s("vegetable", 0.1959f));
        food("dungeonsdelight:taro_milk_tea", s("dairy", 0.4603f), s("fruit", 0.2811f), s("protein", 0.1191f), s("vegetable", 0.1395f));
        food("dungeonsdelight:terrine_loaf", s("grain", 0.3333f), s("protein", 0.6667f));
        food("dungeonsdelight:torchberry_raisins", s("fruit", 1.0f));
        food("dungeonsdelight:tower_boreito", s("grain", 0.2222f), s("protein", 0.7778f));
        food("dungeonsdelight:trial_freakshake", s("dairy", 0.3333f), s("grain", 0.3333f), s("protein", 0.3333f));
        food("dungeonsdelight:trollber_chutney", s("fruit", 1.0f));
        food("dungeonsdelight:venomous_onigiri", s("grain", 0.3333f), s("protein", 0.6667f));
        food("dungeonsdelight:volaille", s("protein", 1.0f));
        food("dungeonsdelight:wardenzola", s("dairy", 0.7222f), s("fruit", 0.2778f));
        food("dungeonsdelight:wardenzola_crumbles", s("fruit", 0.3333f), s("grain", 0.6667f));
        food("dungeonsdelight:wispy_rice_ball", s("grain", 0.6667f), s("vegetable", 0.3333f));
    }

    private static void ends_delight() {
        food("ends_delight:assorted_salad", s("fruit", 0.2761f), s("vegetable", 0.7239f));
        food("ends_delight:bubble_tea", s("dairy", 0.1805f), s("fruit", 0.4623f), s("grain", 0.3573f));
        food("ends_delight:chorus_cookie", s("fruit", 0.0871f), s("grain", 0.9129f));
        food("ends_delight:chorus_flower_pie", s("fruit", 0.4767f), s("grain", 0.5233f));
        food("ends_delight:chorus_flower_tea", s("fruit", 1.0f));
        food("ends_delight:chorus_fruit_grain", s("fruit", 0.5f), s("grain", 0.5f));
        food("ends_delight:chorus_fruit_milk_tea", s("dairy", 0.5556f), s("fruit", 0.4444f));
        food("ends_delight:chorus_fruit_pie", s("fruit", 0.5f), s("grain", 0.5f));
        food("ends_delight:chorus_fruit_pie_slice", s("fruit", 0.5f), s("grain", 0.5f));
        food("ends_delight:chorus_fruit_popsicle", s("fruit", 0.6667f), s("grain", 0.3333f));
        food("ends_delight:chorus_fruit_wine", s("fruit", 1.0f));
        food("ends_delight:chorus_sauce", s("fruit", 1.0f));
        food("ends_delight:dragon_breath_and_chorus_soup", s("fruit", 0.459f), s("protein", 0.1526f), s("vegetable", 0.3884f));
        food("ends_delight:dragon_breath_soda", s("fruit", 1.0f));
        food("ends_delight:dragon_meat_stew", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("ends_delight:dragon_meat_stew_block", s("protein", 0.4631f), s("vegetable", 0.5369f));
        food("ends_delight:dried_chorus_flower", s("fruit", 1.0f));
        food("ends_delight:dried_endermite_meat", s("protein", 1.0f));
        food("ends_delight:end_mixed_salad", s("fruit", 0.0871f), s("grain", 0.0871f), s("vegetable", 0.8259f));
        food("ends_delight:ender_bamboo_rice", s("grain", 0.3046f), s("protein", 0.2288f), s("vegetable", 0.4665f));
        food("ends_delight:ender_congee", s("grain", 0.7057f), s("protein", 0.2943f));
        food("ends_delight:ender_noodle", s("fruit", 0.291f), s("grain", 0.3333f), s("protein", 0.3757f));
        food("ends_delight:ender_pearl_grain", s("grain", 1.0f));
        food("ends_delight:ender_sausage", s("fruit", 0.1888f), s("protein", 0.8112f));
        food("ends_delight:enderman_gristle_stew", s("fruit", 0.6667f), s("protein", 0.1667f), s("vegetable", 0.1667f));
        food("ends_delight:fried_dragon_egg", s("protein", 1.0f));
        food("ends_delight:liquid_dragon_egg", s("protein", 1.0f));
        food("ends_delight:non_hatchable_dragon_egg", s("protein", 1.0f));
        food("ends_delight:raw_dragon_meat", s("protein", 1.0f));
        food("ends_delight:raw_dragon_meat_cuts", s("protein", 1.0f));
        food("ends_delight:raw_ender_mite_meat", s("protein", 1.0f));
        food("ends_delight:raw_ender_sausage", s("fruit", 0.2832f), s("protein", 0.7168f));
        food("ends_delight:roasted_dragon_meat", s("protein", 1.0f));
        food("ends_delight:roasted_dragon_meat_cuts", s("protein", 1.0f));
        food("ends_delight:roasted_dragon_steak", s("fruit", 0.2967f), s("protein", 0.5909f), s("vegetable", 0.1124f));
        food("ends_delight:smoked_dragon_leg", s("protein", 1.0f));
        food("ends_delight:steamed_dragon_egg", s("protein", 1.0f));
        food("ends_delight:stuffed_rice_cake", s("fruit", 0.1381f), s("grain", 0.8619f));
    }

    private static void eternal_starlight_delight() {
        food("eternal_starlight_delight:abyssal_juice", s("fruit", 0.7778f), s("vegetable", 0.2222f));
        food("eternal_starlight_delight:aethersent_flavor_candy", s("fruit", 1.0f));
        food("eternal_starlight_delight:aurora_deer_dice_steak_pasta", s("grain", 0.2596f), s("protein", 0.7404f));
        food("eternal_starlight_delight:aurora_deer_jerky", s("protein", 1.0f));
        food("eternal_starlight_delight:aurora_deer_steak_cuts", s("protein", 1.0f));
        food("eternal_starlight_delight:aurora_deer_steak_special_lunch", s("grain", 0.3692f), s("protein", 0.4913f), s("vegetable", 0.1395f));
        food("eternal_starlight_delight:cooked_aurora_deer_steak_cuts", s("protein", 1.0f));
        food("eternal_starlight_delight:cooked_luminaris_slice", s("protein", 1.0f));
        food("eternal_starlight_delight:cooked_luminofish_slice", s("protein", 1.0f));
        food("eternal_starlight_delight:cooked_ratlin_meat_cuts", s("protein", 1.0f));
        food("eternal_starlight_delight:cooked_seeker_tentacle_cuts", s("protein", 1.0f));
        food("eternal_starlight_delight:cooked_shadow_snail_meat_cuts", s("protein", 1.0f));
        food("eternal_starlight_delight:crinoa_bread", s("grain", 0.8816f), s("protein", 0.1184f));
        food("eternal_starlight_delight:crinoa_dough", s("grain", 0.8224f), s("protein", 0.1776f));
        food("eternal_starlight_delight:dried_rookfish", s("protein", 1.0f));
        food("eternal_starlight_delight:dried_seeker_tentacle_cuts", s("protein", 1.0f));
        food("eternal_starlight_delight:ether_bottle", s("fruit", 1.0f));
        food("eternal_starlight_delight:luminaris_roll", s("grain", 0.6427f), s("protein", 0.3573f));
        food("eternal_starlight_delight:luminaris_slice", s("protein", 1.0f));
        food("eternal_starlight_delight:luminofish_roll", s("grain", 0.4761f), s("protein", 0.5239f));
        food("eternal_starlight_delight:luminofish_slice", s("protein", 1.0f));
        food("eternal_starlight_delight:lunar_berry_pie", s("fruit", 0.5f), s("grain", 0.5f));
        food("eternal_starlight_delight:lunar_berry_pie_slice", s("fruit", 0.5f), s("grain", 0.5f));
        food("eternal_starlight_delight:lunaris_sherbet", s("fruit", 1.0f));
        food("eternal_starlight_delight:marimold_stew", s("protein", 0.5f), s("vegetable", 0.5f));
        food("eternal_starlight_delight:nocturnal_millet_rice", s("grain", 1.0f));
        food("eternal_starlight_delight:pungency_fruit_slice", s("fruit", 1.0f));
        food("eternal_starlight_delight:ratlin_meat_cuts", s("protein", 1.0f));
        food("eternal_starlight_delight:seeker_tentacle_cuts", s("protein", 1.0f));
        food("eternal_starlight_delight:shadow_snail_meat_cuts", s("protein", 1.0f));
        food("eternal_starlight_delight:shadow_snail_pie_slice", s("grain", 0.5f), s("protein", 0.5f));
        food("eternal_starlight_delight:starcore_flavor_candy", s("fruit", 1.0f));
        food("eternal_starlight_delight:starfire_fried_egg", s("protein", 1.0f));
        food("eternal_starlight_delight:starlight_hamburger", s("fruit", 0.1667f), s("grain", 0.258f), s("protein", 0.4086f), s("vegetable", 0.1667f));
        food("eternal_starlight_delight:starlight_soup", s("fruit", 0.6667f), s("protein", 0.1111f), s("vegetable", 0.2222f));
        food("eternal_starlight_delight:starlit_salad", s("vegetable", 1.0f));
        food("eternal_starlight_delight:starmina_noodle_soup", s("fruit", 0.1743f), s("grain", 0.2663f), s("protein", 0.341f), s("vegetable", 0.2185f));
    }

    private static void frenchdelight() {
        food("frenchdelight:baguette", s("grain", 1.0f));
        food("frenchdelight:beef_bourguignon", s("protein", 0.5658f), s("vegetable", 0.4342f));
        food("frenchdelight:butter", s("dairy", 1.0f));
        food("frenchdelight:butter_ham_baguette_sandwich", s("dairy", 0.4444f), s("grain", 0.1111f), s("protein", 0.4444f));
        food("frenchdelight:ham", s("protein", 1.0f));
        food("frenchdelight:ham_baguette_sandwich", s("grain", 0.1667f), s("protein", 0.8333f));
        food("frenchdelight:long_wheat_dough", s("grain", 0.8333f), s("protein", 0.1667f));
        food("frenchdelight:minced_beef_tartare", s("protein", 1.0f));
        food("frenchdelight:quiche_lorraine", s("dairy", 0.3571f), s("grain", 0.0954f), s("protein", 0.5475f));
    }

    private static void fungidelight() {
        food("fungidelight:cleaned_cap", s("vegetable", 1.0f));
        food("fungidelight:cooked_cleaned_cap", s("vegetable", 1.0f));
        food("fungidelight:creamy_morel_soup", s("dairy", 0.0992f), s("protein", 0.1695f), s("vegetable", 0.7313f));
        food("fungidelight:inky_cap_mushroom", s("vegetable", 1.0f));
        food("fungidelight:inky_cap_scrambled_eggs", s("protein", 0.7385f), s("vegetable", 0.2615f));
        food("fungidelight:inky_caps_salad", s("vegetable", 1.0f));
        food("fungidelight:morel_mushroom", s("vegetable", 1.0f));
        food("fungidelight:mutton_chops_with_truffle", s("protein", 0.3226f), s("vegetable", 0.6774f));
        food("fungidelight:pork_marsala_with_mushrooms", s("protein", 0.4491f), s("vegetable", 0.5509f));
        food("fungidelight:rabbit_with_morels", s("protein", 0.4846f), s("vegetable", 0.5154f));
        food("fungidelight:steak_with_mushrooms", s("dairy", 0.101f), s("protein", 0.5242f), s("vegetable", 0.3748f));
        food("fungidelight:stuffed_morels", s("grain", 0.1245f), s("protein", 0.1686f), s("vegetable", 0.7069f));
        food("fungidelight:truffle", s("vegetable", 1.0f));
        food("fungidelight:truffle_ice_cream", s("dairy", 0.4428f), s("vegetable", 0.5572f));
        food("fungidelight:truffle_pasta", s("dairy", 0.0911f), s("grain", 0.2356f), s("protein", 0.162f), s("vegetable", 0.5113f));
        food("fungidelight:truffle_slice", s("vegetable", 1.0f));
    }

    private static void gobberdelight() {
        food("gobberdelight:ender_gobburger", s("grain", 0.2327f), s("protein", 0.3776f), s("vegetable", 0.3897f));
        food("gobberdelight:ender_goo", s("protein", 1.0f));
        food("gobberdelight:ender_gooey_apple", s("fruit", 1.0f));
        food("gobberdelight:ender_gooey_apple_cider", s("fruit", 1.0f));
        food("gobberdelight:ender_gooey_beef", s("protein", 1.0f));
        food("gobberdelight:ender_gooey_beef_slice", s("protein", 1.0f));
        food("gobberdelight:ender_gooey_beefstew", s("protein", 0.7148f), s("vegetable", 0.2852f));
        food("gobberdelight:ender_gooey_bread", s("grain", 0.878f), s("protein", 0.122f));
        food("gobberdelight:ender_gooey_pie", s("grain", 1.0f));
        food("gobberdelight:ender_gooey_pie_1", s("grain", 1.0f));
        food("gobberdelight:ender_gooey_pie_2", s("grain", 1.0f));
        food("gobberdelight:ender_gooey_pie_3", s("grain", 1.0f));
        food("gobberdelight:ender_gooey_pie_slice", s("grain", 1.0f));
        food("gobberdelight:gobburger", s("grain", 0.2327f), s("protein", 0.3776f), s("vegetable", 0.3897f));
        food("gobberdelight:gooey_apple_cider", s("fruit", 1.0f));
        food("gobberdelight:gooey_beef_slice", s("protein", 1.0f));
        food("gobberdelight:gooey_fruit_salad", s("fruit", 0.8333f), s("vegetable", 0.1667f));
        food("gobberdelight:gooey_pie", s("grain", 1.0f));
        food("gobberdelight:gooey_pie_1", s("grain", 1.0f));
        food("gobberdelight:gooey_pie_2", s("grain", 1.0f));
        food("gobberdelight:gooey_pie_3", s("grain", 1.0f));
        food("gobberdelight:gooey_pie_slice", s("grain", 1.0f));
        food("gobberdelight:nether_gobburger", s("grain", 0.2327f), s("protein", 0.3776f), s("vegetable", 0.3897f));
        food("gobberdelight:nether_gooey_apple_cider", s("fruit", 1.0f));
        food("gobberdelight:nether_gooey_beef_slice", s("protein", 1.0f));
        food("gobberdelight:nether_gooey_pie", s("grain", 1.0f));
        food("gobberdelight:nether_gooey_pie_1", s("grain", 1.0f));
        food("gobberdelight:nether_gooey_pie_2", s("grain", 1.0f));
        food("gobberdelight:nether_gooey_pie_3", s("grain", 1.0f));
        food("gobberdelight:nether_gooey_pie_slice", s("grain", 1.0f));
    }

    private static void minersdelight() {
        food("minersdelight:egg_soup_cup", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("minersdelight:glow_ink_pasta", s("fruit", 0.2313f), s("grain", 0.5586f), s("protein", 0.2101f));
        food("minersdelight:pasta_with_veggieballs", s("grain", 0.432f), s("vegetable", 0.568f));
        food("minersdelight:rock_soup_cup", s("protein", 0.3333f), s("vegetable", 0.6667f));
        food("minersdelight:spicy_hoglin_stew_cup", s("protein", 0.5f), s("vegetable", 0.5f));
        food("minersdelight:spicy_noodle_soup_cup", s("grain", 0.5714f), s("protein", 0.1429f), s("vegetable", 0.2857f));
        food("minersdelight:strider_stew_cup", s("protein", 0.5f), s("vegetable", 0.5f));
        food("minersdelight:stuffed_squid", s("grain", 0.3302f), s("protein", 0.5222f), s("vegetable", 0.1476f));
        food("minersdelight:takoyaki", s("grain", 0.2553f), s("protein", 0.5971f), s("vegetable", 0.1475f));
    }

    private static void mynethersdelight() {
        food("mynethersdelight:blue_tenderloin_steak", s("protein", 1.0f));
        food("mynethersdelight:boiled_egg", s("protein", 1.0f));
        food("mynethersdelight:bread_loaf", s("grain", 0.8735f), s("protein", 0.1265f));
        food("mynethersdelight:bullet_pepper", s("vegetable", 1.0f));
        food("mynethersdelight:burnt_roll", s("grain", 0.3333f), s("protein", 0.6667f));
        food("mynethersdelight:chilidog", s("vegetable", 1.0f));
        food("mynethersdelight:cold_striderloaf", s("grain", 0.3333f), s("protein", 0.6667f));
        food("mynethersdelight:cooked_loin", s("protein", 1.0f));
        food("mynethersdelight:crimson_stroganoff", s("dairy", 0.1129f), s("fruit", 0.0806f), s("grain", 0.1805f), s("protein", 0.5427f), s("vegetable", 0.0833f));
        food("mynethersdelight:deviled_egg", s("protein", 0.7239f), s("vegetable", 0.2761f));
        food("mynethersdelight:dried_ghast_with_milk", s("dairy", 0.5138f), s("fruit", 0.1289f), s("grain", 0.3573f));
        food("mynethersdelight:egg_soup", s("protein", 0.7581f), s("vegetable", 0.2419f));
        food("mynethersdelight:enchanted_golden_egg", s("protein", 1.0f));
        food("mynethersdelight:fried_hoglin_chop", s("grain", 0.1375f), s("protein", 0.7249f), s("vegetable", 0.1375f));
        food("mynethersdelight:fries_ghasta", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("mynethersdelight:ghasmati", s("grain", 1.0f));
        food("mynethersdelight:ghast_dough", s("grain", 0.6568f), s("protein", 0.3432f));
        food("mynethersdelight:ghast_salad", s("grain", 0.1591f), s("protein", 0.1591f), s("vegetable", 0.6818f));
        food("mynethersdelight:ghast_sourdough", s("grain", 0.8103f), s("protein", 0.1897f));
        food("mynethersdelight:ghasta", s("protein", 1.0f));
        food("mynethersdelight:ghasta_with_cream", s("dairy", 0.3333f), s("grain", 0.6667f));
        food("mynethersdelight:giant_takoyaki", s("grain", 0.2076f), s("protein", 0.6204f), s("vegetable", 0.172f));
        food("mynethersdelight:golden_egg", s("protein", 1.0f));
        food("mynethersdelight:hoglin_loin", s("protein", 1.0f));
        food("mynethersdelight:hoglin_sausage", s("protein", 1.0f));
        food("mynethersdelight:hot_cream", s("dairy", 1.0f));
        food("mynethersdelight:hot_cream_cone", s("dairy", 1.0f));
        food("mynethersdelight:hot_wings", s("protein", 0.546f), s("vegetable", 0.454f));
        food("mynethersdelight:hotdog", s("grain", 0.3794f), s("protein", 0.6206f));
        food("mynethersdelight:hotdog_with_mixed_salad", s("grain", 0.2432f), s("protein", 0.4221f), s("vegetable", 0.3348f));
        food("mynethersdelight:hotdog_with_nether_salad", s("grain", 0.2479f), s("protein", 0.4299f), s("vegetable", 0.3222f));
        food("mynethersdelight:magma_cake_block", s("grain", 1.0f));
        food("mynethersdelight:magma_cake_slice", s("grain", 1.0f));
        food("mynethersdelight:minced_strider", s("protein", 1.0f));
        food("mynethersdelight:nether_burger", s("grain", 0.3381f), s("protein", 0.6619f));
        food("mynethersdelight:pepper_powder", s("vegetable", 1.0f));
        food("mynethersdelight:roast_ear", s("vegetable", 1.0f));
        food("mynethersdelight:roast_stuffed_hoglin", s("protein", 0.3333f), s("vegetable", 0.6667f));
        food("mynethersdelight:roasted_sausage", s("protein", 1.0f));
        food("mynethersdelight:rock_soup", s("protein", 0.7778f), s("vegetable", 0.2222f));
        food("mynethersdelight:sausage_and_potatoes", s("protein", 0.6401f), s("vegetable", 0.3599f));
        food("mynethersdelight:scotch_eggs", s("grain", 0.1694f), s("protein", 0.8306f));
        food("mynethersdelight:sizzling_pudding", s("dairy", 0.3445f), s("grain", 0.2912f), s("protein", 0.1911f), s("vegetable", 0.1732f));
        food("mynethersdelight:slices_of_bread", s("grain", 1.0f));
        food("mynethersdelight:spicy_curry", s("dairy", 0.092f), s("grain", 0.1821f), s("protein", 0.3071f), s("vegetable", 0.4189f));
        food("mynethersdelight:spicy_hoglin_stew", s("protein", 0.1667f), s("vegetable", 0.8333f));
        food("mynethersdelight:spicy_noodle_soup", s("grain", 0.1905f), s("protein", 0.5751f), s("vegetable", 0.2344f));
        food("mynethersdelight:strider_egg", s("protein", 1.0f));
        food("mynethersdelight:strider_slice", s("protein", 1.0f));
        food("mynethersdelight:strider_stew", s("protein", 0.8333f), s("vegetable", 0.1667f));
        food("mynethersdelight:strider_with_grilled_fungus", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("mynethersdelight:striderloaf", s("grain", 0.3333f), s("protein", 0.6667f));
        food("mynethersdelight:stuffed_pepper", s("dairy", 0.105f), s("protein", 0.3287f), s("vegetable", 0.5662f));
        food("mynethersdelight:tear_popsicle", s("fruit", 1.0f));
        food("mynethersdelight:toasts", s("grain", 1.0f));
        food("mynethersdelight:twisted_ghasta", s("protein", 1.0f));
    }

    private static void natures_delight() {
        food("natures_delight:alfredo_pasta", s("grain", 0.4921f), s("protein", 0.5079f));
        food("natures_delight:cocada", s("dairy", 0.2003f), s("fruit", 0.6818f), s("protein", 0.1178f));
        food("natures_delight:coconut_bread", s("fruit", 0.3528f), s("grain", 0.4262f), s("protein", 0.221f));
        food("natures_delight:coconut_pancakes", s("dairy", 0.1426f), s("fruit", 0.4287f), s("grain", 0.4287f));
        food("natures_delight:coconut_sauce", s("fruit", 1.0f));
        food("natures_delight:fafaru", s("fruit", 0.1798f), s("protein", 0.5979f), s("vegetable", 0.2222f));
        food("natures_delight:manakish", s("grain", 0.6075f), s("protein", 0.3925f));
        food("natures_delight:sweet_and_savory_saute", s("fruit", 0.1696f), s("grain", 0.1696f), s("protein", 0.1111f), s("vegetable", 0.5498f));
        food("natures_delight:turnip_tagine", s("vegetable", 1.0f));
    }

    private static void nydelight() {
        food("nydelight:adzuki_beans", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("nydelight:cooked_sea_bream", s("protein", 1.0f));
        food("nydelight:datemaki", s("fruit", 0.3333f), s("protein", 0.6667f));
        food("nydelight:kurikinton", s("protein", 0.1111f), s("vegetable", 0.8889f));
        food("nydelight:kuromame", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("nydelight:ozoni", s("grain", 0.2222f), s("protein", 0.4108f), s("vegetable", 0.367f));
        food("nydelight:toshikoshi_soba", s("grain", 0.7239f), s("vegetable", 0.2761f));
    }

    private static void oceansdelight() {
        food("oceansdelight:bowl_of_guardian_soup", s("protein", 0.3333f), s("vegetable", 0.6667f));
        food("oceansdelight:braised_sea_pickle", s("protein", 0.2603f), s("vegetable", 0.7397f));
        food("oceansdelight:cabbage_wrapped_elder_guardian", s("protein", 0.2021f), s("vegetable", 0.7979f));
        food("oceansdelight:cooked_elder_guardian_slice", s("protein", 1.0f));
        food("oceansdelight:cooked_guardian_tail", s("protein", 1.0f));
        food("oceansdelight:cooked_stuffed_cod", s("protein", 0.7054f), s("vegetable", 0.2946f));
        food("oceansdelight:cooked_stuffed_squid", s("grain", 0.2603f), s("protein", 0.5556f), s("vegetable", 0.1841f));
        food("oceansdelight:elder_guardian_roll", s("grain", 0.7003f), s("protein", 0.2997f));
        food("oceansdelight:elder_guardian_slice", s("protein", 1.0f));
        food("oceansdelight:fugu_roll", s("grain", 0.5337f), s("protein", 0.4663f));
        food("oceansdelight:fugu_slice", s("protein", 1.0f));
        food("oceansdelight:guardian_soup", s("protein", 0.3956f), s("vegetable", 0.6044f));
        food("oceansdelight:honey_fried_kelp", s("fruit", 0.5845f), s("vegetable", 0.4155f));
        food("oceansdelight:kelp_encrusted_cod", s("grain", 0.1146f), s("protein", 0.5865f), s("vegetable", 0.2989f));
        food("oceansdelight:seagrass_salad", s("vegetable", 1.0f));
        food("oceansdelight:squid_rings", s("grain", 0.4047f), s("protein", 0.4912f), s("vegetable", 0.104f));
        food("oceansdelight:stuffed_cod", s("protein", 0.5582f), s("vegetable", 0.4418f));
        food("oceansdelight:stuffed_squid", s("grain", 0.3905f), s("protein", 0.3333f), s("vegetable", 0.2761f));
    }

    private static void ramadandelight() {
        food("ramadandelight:bourek", s("grain", 0.4246f), s("protein", 0.3454f), s("vegetable", 0.23f));
        food("ramadandelight:chickpea", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("ramadandelight:chickpea_and_rice", s("grain", 0.4118f), s("protein", 0.2405f), s("vegetable", 0.3477f));
        food("ramadandelight:chorba", s("protein", 0.3802f), s("vegetable", 0.6198f));
        food("ramadandelight:date", s("fruit", 1.0f));
        food("ramadandelight:date_stuffed_cookie", s("fruit", 0.7221f), s("grain", 0.2779f));
        food("ramadandelight:date_syrup", s("fruit", 1.0f));
        food("ramadandelight:flat_bread", s("grain", 0.8869f), s("protein", 0.1131f));
        food("ramadandelight:haleem", s("grain", 0.4304f), s("protein", 0.3614f), s("vegetable", 0.2082f));
        food("ramadandelight:harira", s("protein", 0.2637f), s("vegetable", 0.7363f));
        food("ramadandelight:hummus_tahini", s("grain", 0.2222f), s("protein", 0.5185f), s("vegetable", 0.2593f));
        food("ramadandelight:kebab", s("protein", 1.0f));
        food("ramadandelight:luqaimat", s("fruit", 0.1194f), s("grain", 0.7675f), s("protein", 0.1131f));
        food("ramadandelight:mahalabia", s("dairy", 0.5337f), s("fruit", 0.3485f), s("protein", 0.1178f));
        food("ramadandelight:parsley", s("vegetable", 1.0f));
        food("ramadandelight:samosa", s("grain", 0.4755f), s("protein", 0.2049f), s("vegetable", 0.3196f));
        food("ramadandelight:savory_filling", s("protein", 0.4659f), s("vegetable", 0.5341f));
        food("ramadandelight:sayadieh", s("grain", 0.3776f), s("protein", 0.3504f), s("vegetable", 0.272f));
        food("ramadandelight:small_dough", s("grain", 0.7381f), s("protein", 0.1579f), s("vegetable", 0.104f));
        food("ramadandelight:sweet_tagine", s("fruit", 0.5582f), s("protein", 0.2196f), s("vegetable", 0.2222f));
        food("ramadandelight:tagine", s("protein", 0.4348f), s("vegetable", 0.5652f));
        food("ramadandelight:zalabiyeh", s("fruit", 0.1111f), s("grain", 0.627f), s("protein", 0.1579f), s("vegetable", 0.104f));
    }

    private static void rice_delight() {
        food("rice_delight:bc_burrito", s("grain", 0.7398f), s("protein", 0.1735f), s("vegetable", 0.0867f));
        food("rice_delight:be_burrito", s("grain", 0.6835f), s("protein", 0.3165f));
        food("rice_delight:bell_pepper", s("vegetable", 1.0f));
        food("rice_delight:bowl_of_apple_mochi", s("fruit", 0.6095f), s("grain", 0.3905f));
        food("rice_delight:bowl_of_chocolate_mochi", s("fruit", 0.5075f), s("grain", 0.4925f));
        food("rice_delight:bowl_of_glow_berry_mochi", s("fruit", 0.5556f), s("grain", 0.4444f));
        food("rice_delight:bowl_of_jollof_rice", s("grain", 0.4867f), s("protein", 0.1085f), s("vegetable", 0.4048f));
        food("rice_delight:bowl_of_melon_mochi", s("fruit", 0.5556f), s("grain", 0.4444f));
        food("rice_delight:bowl_of_risotto", s("grain", 0.6095f), s("protein", 0.1953f), s("vegetable", 0.1953f));
        food("rice_delight:bowl_of_sweet_berry_mochi", s("fruit", 0.5556f), s("grain", 0.4444f));
        food("rice_delight:bt_burrito", s("grain", 0.7398f), s("protein", 0.1735f), s("vegetable", 0.0867f));
        food("rice_delight:burnt_burrito", s("grain", 0.6584f), s("protein", 0.1745f), s("vegetable", 0.1671f));
        food("rice_delight:burnt_sliced_burrito", s("grain", 1.0f));
        food("rice_delight:burnt_wrap", s("grain", 1.0f));
        food("rice_delight:cbc_burrito", s("grain", 0.7044f), s("protein", 0.1372f), s("vegetable", 0.1584f));
        food("rice_delight:chopped_scallions", s("vegetable", 1.0f));
        food("rice_delight:cinnamon_apple_rice_bowl", s("fruit", 0.5572f), s("grain", 0.4428f));
        food("rice_delight:cooked_wrap", s("grain", 1.0f));
        food("rice_delight:fv_burrito", s("grain", 0.6889f), s("vegetable", 0.3111f));
        food("rice_delight:horchata", s("dairy", 0.4984f), s("grain", 0.5016f));
        food("rice_delight:omelette", s("protein", 1.0f));
        food("rice_delight:omelette_roll", s("grain", 0.5152f), s("protein", 0.4848f));
        food("rice_delight:omurice", s("grain", 0.6206f), s("protein", 0.2622f), s("vegetable", 0.1173f));
        food("rice_delight:pepper_chunk", s("vegetable", 1.0f));
        food("rice_delight:raw_wrap", s("grain", 0.8816f), s("protein", 0.1184f));
        food("rice_delight:rice_balls", s("grain", 1.0f));
        food("rice_delight:rice_dough", s("grain", 1.0f));
        food("rice_delight:rice_filled_bell_pepper", s("grain", 0.4818f), s("vegetable", 0.5182f));
        food("rice_delight:rice_wafer", s("grain", 1.0f));
        food("rice_delight:sliced_bc_burrito", s("grain", 1.0f));
        food("rice_delight:sliced_be_burrito", s("grain", 1.0f));
        food("rice_delight:sliced_bt_burrito", s("grain", 1.0f));
        food("rice_delight:sliced_burnt_burrito", s("grain", 1.0f));
        food("rice_delight:sliced_cbc_burrito", s("grain", 1.0f));
        food("rice_delight:sliced_fv_burrito", s("grain", 1.0f));
        food("rice_delight:sliced_v_burrito", s("grain", 1.0f));
        food("rice_delight:v_burrito", s("grain", 0.8006f), s("vegetable", 0.1994f));
    }

    private static void roll_delight() {
        food("roll_delight:amazing_salmon_roll", s("grain", 0.4411f), s("protein", 0.3908f), s("vegetable", 0.1681f));
        food("roll_delight:amazing_salmon_roll_slice", s("grain", 0.5f), s("protein", 0.5f));
        food("roll_delight:ancient_roll", s("grain", 0.7468f), s("vegetable", 0.2532f));
        food("roll_delight:ancient_roll_slice", s("grain", 1.0f));
        food("roll_delight:cooked_nether_wart", s("vegetable", 1.0f));
        food("roll_delight:golden_roll", s("grain", 0.3333f), s("vegetable", 0.6667f));
        food("roll_delight:golden_roll_slice", s("grain", 1.0f));
        food("roll_delight:legendary_roll_medley", s("grain", 0.75f), s("protein", 0.125f), s("vegetable", 0.125f));
        food("roll_delight:mushroom_roll", s("grain", 0.5174f), s("vegetable", 0.4826f));
        food("roll_delight:mushroom_roll_slice", s("grain", 0.5f), s("vegetable", 0.5f));
        food("roll_delight:mythical_roll_medley", s("grain", 1.0f));
        food("roll_delight:nether_roll", s("grain", 0.3333f), s("protein", 0.4734f), s("vegetable", 0.1933f));
        food("roll_delight:rice_roll", s("grain", 0.8067f), s("vegetable", 0.1933f));
        food("roll_delight:rice_roll_slice", s("grain", 1.0f));
        food("roll_delight:tobiko_roll", s("grain", 1.0f));
    }

    private static void rusticdelight1() {
        food("rusticdelight:baked_potato_slices", s("vegetable", 1.0f));
        food("rusticdelight:batter", s("dairy", 0.1084f), s("grain", 0.7005f), s("protein", 0.1911f));
        food("rusticdelight:bell_pepper_black", s("vegetable", 1.0f));
        food("rusticdelight:bell_pepper_blue", s("vegetable", 1.0f));
        food("rusticdelight:bell_pepper_green", s("vegetable", 1.0f));
        food("rusticdelight:bell_pepper_medley", s("grain", 0.1484f), s("protein", 0.1122f), s("vegetable", 0.7393f));
        food("rusticdelight:bell_pepper_orange", s("vegetable", 1.0f));
        food("rusticdelight:bell_pepper_pasta", s("grain", 0.2371f), s("protein", 0.1106f), s("vegetable", 0.6523f));
        food("rusticdelight:bell_pepper_pink", s("vegetable", 1.0f));
        food("rusticdelight:bell_pepper_purple", s("vegetable", 1.0f));
        food("rusticdelight:bell_pepper_red", s("vegetable", 1.0f));
        food("rusticdelight:bell_pepper_roll_black", s("grain", 0.4761f), s("vegetable", 0.5239f));
        food("rusticdelight:bell_pepper_roll_blue", s("grain", 0.4761f), s("vegetable", 0.5239f));
        food("rusticdelight:bell_pepper_roll_green", s("grain", 0.4761f), s("vegetable", 0.5239f));
        food("rusticdelight:bell_pepper_roll_orange", s("grain", 0.4761f), s("vegetable", 0.5239f));
        food("rusticdelight:bell_pepper_roll_pink", s("grain", 0.4761f), s("vegetable", 0.5239f));
        food("rusticdelight:bell_pepper_roll_purple", s("grain", 0.4761f), s("vegetable", 0.5239f));
        food("rusticdelight:bell_pepper_roll_red", s("grain", 0.4761f), s("vegetable", 0.5239f));
        food("rusticdelight:bell_pepper_roll_white", s("grain", 0.4761f), s("vegetable", 0.5239f));
        food("rusticdelight:bell_pepper_roll_yellow", s("grain", 0.4761f), s("vegetable", 0.5239f));
        food("rusticdelight:bell_pepper_slice_black", s("vegetable", 1.0f));
        food("rusticdelight:bell_pepper_slice_blue", s("vegetable", 1.0f));
        food("rusticdelight:bell_pepper_slice_green", s("vegetable", 1.0f));
        food("rusticdelight:bell_pepper_slice_orange", s("vegetable", 1.0f));
        food("rusticdelight:bell_pepper_slice_pink", s("vegetable", 1.0f));
        food("rusticdelight:bell_pepper_slice_purple", s("vegetable", 1.0f));
        food("rusticdelight:bell_pepper_slice_red", s("vegetable", 1.0f));
        food("rusticdelight:bell_pepper_slice_white", s("vegetable", 1.0f));
        food("rusticdelight:bell_pepper_slice_yellow", s("vegetable", 1.0f));
        food("rusticdelight:bell_pepper_soup", s("vegetable", 1.0f));
        food("rusticdelight:bell_pepper_white", s("vegetable", 1.0f));
        food("rusticdelight:bell_pepper_yellow", s("vegetable", 1.0f));
        food("rusticdelight:calamari", s("protein", 1.0f));
        food("rusticdelight:calamari_roll", s("grain", 0.5f), s("protein", 0.5f));
        food("rusticdelight:calamari_slice", s("protein", 1.0f));
        food("rusticdelight:calamari_soup", s("dairy", 0.1018f), s("protein", 0.4129f), s("vegetable", 0.4853f));
        food("rusticdelight:cherry_blossom_cheesecake", s("dairy", 0.4f), s("fruit", 0.4f), s("grain", 0.2f));
        food("rusticdelight:cherry_blossom_cheesecake_slice", s("dairy", 0.4f), s("fruit", 0.4f), s("grain", 0.2f));
        food("rusticdelight:cherry_blossom_coffee", s("dairy", 0.0871f), s("fruit", 0.5249f), s("protein", 0.2587f), s("vegetable", 0.1293f));
        food("rusticdelight:cherry_blossom_cookie", s("fruit", 0.1667f), s("grain", 0.8333f));
        food("rusticdelight:cherry_blossom_pancake", s("fruit", 0.5f), s("grain", 0.5f));
        food("rusticdelight:cherry_blossom_pancakes", s("fruit", 0.5f), s("grain", 0.5f));
        food("rusticdelight:cherry_blossom_roll", s("fruit", 0.1667f), s("grain", 0.8333f));
        food("rusticdelight:chocolate_coffee", s("dairy", 0.1272f), s("fruit", 0.7664f), s("protein", 0.1064f));
        food("rusticdelight:chocolate_pancake", s("fruit", 0.5292f), s("grain", 0.4708f));
        food("rusticdelight:chocolate_pancakes", s("dairy", 0.0896f), s("fruit", 0.5798f), s("grain", 0.3307f));
        food("rusticdelight:coffee", s("fruit", 0.5f), s("protein", 0.3333f), s("vegetable", 0.1667f));
        food("rusticdelight:coffee_beans", s("fruit", 0.25f), s("protein", 0.5f), s("vegetable", 0.25f));
        food("rusticdelight:coffee_braised_beef", s("fruit", 0.2125f), s("protein", 0.4577f), s("vegetable", 0.3298f));
        food("rusticdelight:coffee_cheesecake", s("dairy", 0.5f), s("fruit", 0.25f), s("grain", 0.25f));
        food("rusticdelight:coffee_cheesecake_slice", s("dairy", 0.5f), s("fruit", 0.25f), s("grain", 0.25f));
        food("rusticdelight:coffee_cookie", s("fruit", 0.1765f), s("grain", 0.7059f), s("protein", 0.1176f));
        food("rusticdelight:coffee_pancake", s("fruit", 0.3016f), s("grain", 0.4385f), s("protein", 0.1785f), s("vegetable", 0.0814f));
        food("rusticdelight:coffee_pancakes", s("fruit", 0.2857f), s("grain", 0.3245f), s("protein", 0.2677f), s("vegetable", 0.1222f));
        food("rusticdelight:cooked_calamari", s("protein", 1.0f));
        food("rusticdelight:cooked_calamari_slice", s("protein", 1.0f));
        food("rusticdelight:dark_bell_pepper_medley", s("grain", 0.1484f), s("protein", 0.1122f), s("vegetable", 0.7393f));
        food("rusticdelight:dark_coffee", s("fruit", 0.5f), s("protein", 0.3333f), s("vegetable", 0.1667f));
        food("rusticdelight:fried_calamari", s("grain", 0.1867f), s("protein", 0.6248f), s("vegetable", 0.1885f));
        food("rusticdelight:fried_chicken", s("grain", 0.1644f), s("protein", 0.6009f), s("vegetable", 0.2347f));
        food("rusticdelight:fried_dough", s("grain", 0.7381f), s("protein", 0.1579f), s("vegetable", 0.104f));
        food("rusticdelight:fried_dumplings", s("grain", 0.6502f), s("protein", 0.1714f), s("vegetable", 0.1784f));
        food("rusticdelight:fried_fish", s("grain", 0.2484f), s("protein", 0.7516f));
        food("rusticdelight:fried_mushrooms", s("protein", 0.2603f), s("vegetable", 0.7397f));
        food("rusticdelight:fruit_beignet", s("fruit", 0.6908f), s("grain", 0.2224f), s("protein", 0.0868f));
        food("rusticdelight:golden_coffee_beans", s("fruit", 0.25f), s("protein", 0.5f), s("vegetable", 0.25f));
        food("rusticdelight:honey_coffee", s("fruit", 1.0f));
        food("rusticdelight:honey_pancake", s("fruit", 0.3333f), s("grain", 0.6667f));
        food("rusticdelight:honey_pancakes", s("fruit", 0.3333f), s("grain", 0.6667f));
        food("rusticdelight:milk_coffee", s("dairy", 0.3093f), s("fruit", 0.3027f), s("protein", 0.2587f), s("vegetable", 0.1293f));
        food("rusticdelight:pale_bell_pepper_medley", s("grain", 0.1484f), s("protein", 0.1122f), s("vegetable", 0.7393f));
        food("rusticdelight:pancake", s("grain", 1.0f));
        food("rusticdelight:pancakes", s("grain", 1.0f));
        food("rusticdelight:potato_salad", s("dairy", 0.1138f), s("protein", 0.2007f), s("vegetable", 0.6855f));
        food("rusticdelight:potato_slices", s("vegetable", 1.0f));
        food("rusticdelight:pumpkin_coffee", s("dairy", 0.1005f), s("fruit", 0.2188f), s("vegetable", 0.6808f));
        food("rusticdelight:pumpkin_pancake", s("grain", 0.339f), s("vegetable", 0.661f));
        food("rusticdelight:pumpkin_pancakes", s("grain", 0.2585f), s("vegetable", 0.7415f));
        food("rusticdelight:rice_roll_royale", s("grain", 0.7469f), s("vegetable", 0.2531f));
        food("rusticdelight:roasted_bell_pepper_black", s("vegetable", 1.0f));
        food("rusticdelight:roasted_bell_pepper_blue", s("vegetable", 1.0f));
        food("rusticdelight:roasted_bell_pepper_green", s("vegetable", 1.0f));
        food("rusticdelight:roasted_bell_pepper_orange", s("vegetable", 1.0f));
        food("rusticdelight:roasted_bell_pepper_pink", s("vegetable", 1.0f));
        food("rusticdelight:roasted_bell_pepper_purple", s("vegetable", 1.0f));
        food("rusticdelight:roasted_bell_pepper_red", s("vegetable", 1.0f));
        food("rusticdelight:roasted_bell_pepper_slice_black", s("vegetable", 1.0f));
        food("rusticdelight:roasted_bell_pepper_slice_blue", s("vegetable", 1.0f));
        food("rusticdelight:roasted_bell_pepper_slice_green", s("vegetable", 1.0f));
        food("rusticdelight:roasted_bell_pepper_slice_orange", s("vegetable", 1.0f));
        food("rusticdelight:roasted_bell_pepper_slice_pink", s("vegetable", 1.0f));
        food("rusticdelight:roasted_bell_pepper_slice_purple", s("vegetable", 1.0f));
        food("rusticdelight:roasted_bell_pepper_slice_red", s("vegetable", 1.0f));
        food("rusticdelight:roasted_bell_pepper_slice_white", s("vegetable", 1.0f));
        food("rusticdelight:roasted_bell_pepper_slice_yellow", s("vegetable", 1.0f));
        food("rusticdelight:roasted_bell_pepper_white", s("vegetable", 1.0f));
        food("rusticdelight:roasted_bell_pepper_yellow", s("vegetable", 1.0f));
        food("rusticdelight:roasted_coffee_beans", s("fruit", 0.25f), s("protein", 0.5f), s("vegetable", 0.25f));
        food("rusticdelight:spring_rolls", s("grain", 0.4816f), s("protein", 0.1477f), s("vegetable", 0.3707f));
        food("rusticdelight:stuffed_bell_pepper_black", s("grain", 0.2227f), s("protein", 0.1683f), s("vegetable", 0.609f));
        food("rusticdelight:stuffed_bell_pepper_blue", s("grain", 0.2227f), s("protein", 0.1683f), s("vegetable", 0.609f));
        food("rusticdelight:stuffed_bell_pepper_green", s("grain", 0.2227f), s("protein", 0.1683f), s("vegetable", 0.609f));
        food("rusticdelight:stuffed_bell_pepper_orange", s("grain", 0.2227f), s("protein", 0.1683f), s("vegetable", 0.609f));
        food("rusticdelight:stuffed_bell_pepper_pink", s("grain", 0.2227f), s("protein", 0.1683f), s("vegetable", 0.609f));
        food("rusticdelight:stuffed_bell_pepper_purple", s("grain", 0.2227f), s("protein", 0.1683f), s("vegetable", 0.609f));
        food("rusticdelight:stuffed_bell_pepper_red", s("grain", 0.2227f), s("protein", 0.1683f), s("vegetable", 0.609f));
        food("rusticdelight:stuffed_bell_pepper_white", s("grain", 0.2227f), s("protein", 0.1683f), s("vegetable", 0.609f));
        food("rusticdelight:stuffed_bell_pepper_yellow", s("grain", 0.2227f), s("protein", 0.1683f), s("vegetable", 0.609f));
        food("rusticdelight:sweet_salad", s("fruit", 0.3928f), s("vegetable", 0.6072f));
        food("rusticdelight:syrup", s("fruit", 0.6667f), s("vegetable", 0.3333f));
    }

    private static void rusticdelight2() {
        food("rusticdelight:syrup_cheesecake", s("dairy", 0.6667f), s("grain", 0.3333f));
        food("rusticdelight:syrup_cheesecake_slice", s("dairy", 0.6667f), s("grain", 0.3333f));
        food("rusticdelight:syrup_coffee", s("dairy", 0.1031f), s("fruit", 0.6564f), s("protein", 0.0862f), s("vegetable", 0.1542f));
        food("rusticdelight:syrup_cookie", s("fruit", 0.16f), s("grain", 0.84f));
        food("rusticdelight:syrup_sandwich", s("fruit", 0.2097f), s("grain", 0.657f), s("vegetable", 0.1333f));
        food("rusticdelight:vegetable_pancake", s("dairy", 0.0844f), s("grain", 0.3868f), s("vegetable", 0.5288f));
        food("rusticdelight:vegetable_pancakes", s("dairy", 0.1266f), s("grain", 0.3302f), s("vegetable", 0.5431f));
    }

    private static void twilightdelight() {
        food("twilightdelight:aurora_pie", s("grain", 1.0f));
        food("twilightdelight:aurora_pie_slice", s("grain", 1.0f));
        food("twilightdelight:borer_tear_soup", s("protein", 0.1111f), s("vegetable", 0.8889f));
        food("twilightdelight:chocolate_wafer", s("fruit", 0.5318f), s("grain", 0.4682f));
        food("twilightdelight:cooked_insect", s("protein", 1.0f));
        food("twilightdelight:cooked_meef_slice", s("protein", 1.0f));
        food("twilightdelight:cooked_tomahawk_smeak", s("protein", 1.0f));
        food("twilightdelight:cooked_venison_rib", s("protein", 1.0f));
        food("twilightdelight:fried_insect", s("protein", 0.3333f), s("vegetable", 0.6667f));
        food("twilightdelight:ghast_brain_salad", s("protein", 0.1667f), s("vegetable", 0.8333f));
        food("twilightdelight:ghast_burger", s("grain", 0.4028f), s("protein", 0.2321f), s("vegetable", 0.365f));
        food("twilightdelight:glacier_ice_tea", s("fruit", 1.0f));
        food("twilightdelight:glow_venison_rib_with_pasta", s("fruit", 0.1199f), s("grain", 0.3065f), s("protein", 0.4164f), s("vegetable", 0.1571f));
        food("twilightdelight:glowstew", s("fruit", 0.6667f), s("protein", 0.1667f), s("vegetable", 0.1667f));
        food("twilightdelight:grilled_ghast", s("grain", 0.3905f), s("protein", 0.3333f), s("vegetable", 0.2761f));
        food("twilightdelight:grilled_tomahawk_smeak", s("dairy", 0.1805f), s("fruit", 0.1289f), s("protein", 0.3991f), s("vegetable", 0.2915f));
        food("twilightdelight:hydra_burger", s("grain", 0.2522f), s("protein", 0.3727f), s("vegetable", 0.3752f));
        food("twilightdelight:hydra_piece", s("protein", 1.0f));
        food("twilightdelight:liveroot_pork_fried_rice", s("grain", 0.3204f), s("protein", 0.6796f));
        food("twilightdelight:liveroot_venison_noodle_soup", s("grain", 0.1968f), s("protein", 0.5309f), s("vegetable", 0.2723f));
        food("twilightdelight:meef_wrap", s("grain", 0.5003f), s("protein", 0.1757f), s("vegetable", 0.324f));
        food("twilightdelight:mushgloom_meef_pasta", s("grain", 0.5062f), s("protein", 0.3125f), s("vegetable", 0.1813f));
        food("twilightdelight:mushgloom_sauce", s("protein", 0.1841f), s("vegetable", 0.8159f));
        food("twilightdelight:phytochemical_juice", s("fruit", 1.0f));
        food("twilightdelight:tear_drink", s("fruit", 1.0f));
        food("twilightdelight:thorn_rose_tea", s("fruit", 1.0f));
        food("twilightdelight:thousand_plant_stew", s("protein", 0.5f), s("vegetable", 0.5f));
        food("twilightdelight:torchberry_cookie", s("fruit", 0.3889f), s("grain", 0.6111f));
        food("twilightdelight:torchberry_juice", s("fruit", 1.0f));
        food("twilightdelight:torchberry_pie", s("fruit", 0.5f), s("grain", 0.5f));
        food("twilightdelight:torchberry_pie_slice", s("fruit", 0.5f), s("grain", 0.5f));
        food("twilightdelight:torchberry_venison_sandwich", s("fruit", 0.2773f), s("grain", 0.2769f), s("protein", 0.2874f), s("vegetable", 0.1584f));
    }

    private static void undergardendelight() {
        food("undergardendelight:baked_gwibling_and_vegetables", s("protein", 0.3035f), s("vegetable", 0.6965f));
        food("undergardendelight:blisterberry_juice", s("fruit", 1.0f));
        food("undergardendelight:blisterberry_pie", s("fruit", 0.5f), s("grain", 0.5f));
        food("undergardendelight:blisterberry_pie_slice", s("fruit", 0.5f), s("grain", 0.5f));
        food("undergardendelight:blisterberry_popsicle", s("fruit", 1.0f));
        food("undergardendelight:blood_brew", s("protein", 1.0f));
        food("undergardendelight:blood_tomato_soup", s("protein", 0.5111f), s("vegetable", 0.4889f));
        food("undergardendelight:boiled_mogmoss", s("vegetable", 1.0f));
        food("undergardendelight:cooked_dweller_meat_slice", s("protein", 1.0f));
        food("undergardendelight:cooked_gloomper_cuts", s("protein", 1.0f));
        food("undergardendelight:cooked_gwibfillet", s("protein", 1.0f));
        food("undergardendelight:cooked_gwibsteak", s("protein", 1.0f));
        food("undergardendelight:depth_berry_salad", s("fruit", 0.8333f), s("vegetable", 0.1667f));
        food("undergardendelight:depth_shroom_cream_soup", s("dairy", 0.2876f), s("vegetable", 0.7124f));
        food("undergardendelight:depthflower_tea", s("dairy", 0.3333f), s("fruit", 0.3333f), s("grain", 0.3333f));
        food("undergardendelight:ditchbulb_pasta", s("grain", 0.5062f), s("protein", 0.2716f), s("vegetable", 0.2222f));
        food("undergardendelight:ditchbulb_sauce", s("vegetable", 1.0f));
        food("undergardendelight:droopfruit_custard", s("dairy", 0.4f), s("fruit", 0.4f), s("protein", 0.2f));
        food("undergardendelight:droopfruit_juice", s("fruit", 1.0f));
        food("undergardendelight:droopfruit_pie", s("fruit", 0.5f), s("grain", 0.5f));
        food("undergardendelight:droopfruit_pie_slice", s("fruit", 0.5f), s("grain", 0.5f));
        food("undergardendelight:droopfruit_popsicle", s("fruit", 1.0f));
        food("undergardendelight:droopfruit_salad", s("dairy", 0.1667f), s("fruit", 0.5f), s("grain", 0.1667f), s("vegetable", 0.1667f));
        food("undergardendelight:droopstew", s("fruit", 0.2157f), s("protein", 0.3428f), s("vegetable", 0.4415f));
        food("undergardendelight:dweller_meat_slice", s("protein", 1.0f));
        food("undergardendelight:glitterdish", s("fruit", 0.367f), s("protein", 0.1111f), s("vegetable", 0.5219f));
        food("undergardendelight:glitterkelp_roll", s("grain", 0.5239f), s("vegetable", 0.4761f));
        food("undergardendelight:glitterkelp_roll_slice", s("grain", 0.5f), s("vegetable", 0.5f));
        food("undergardendelight:glitterwrap", s("grain", 0.3398f), s("protein", 0.1779f), s("vegetable", 0.4823f));
        food("undergardendelight:gloomgourd_juice", s("vegetable", 1.0f));
        food("undergardendelight:gloomgourd_pie_slice", s("grain", 0.5f), s("vegetable", 0.5f));
        food("undergardendelight:gloomper_and_gloomgourd_stew", s("protein", 0.6554f), s("vegetable", 0.3446f));
        food("undergardendelight:gloomper_fresh_salad", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("undergardendelight:greater_dweller_hamleg", s("protein", 1.0f));
        food("undergardendelight:gronglet_roll", s("grain", 1.0f));
        food("undergardendelight:gronglet_with_roasted_veggies", s("vegetable", 1.0f));
        food("undergardendelight:gronglunch", s("protein", 0.4826f), s("vegetable", 0.5174f));
        food("undergardendelight:gwibfillet_roll", s("grain", 0.8333f), s("protein", 0.1667f));
        food("undergardendelight:mogmoss_slice", s("vegetable", 1.0f));
        food("undergardendelight:mogsteak", s("fruit", 0.2997f), s("protein", 0.4557f), s("vegetable", 0.2447f));
        food("undergardendelight:mushroom_ink_pasta", s("grain", 0.4259f), s("protein", 0.4074f), s("vegetable", 0.1667f));
        food("undergardendelight:raw_gloomper_cuts", s("protein", 1.0f));
        food("undergardendelight:raw_gwibsteak", s("protein", 1.0f));
        food("undergardendelight:scintling_stew", s("fruit", 0.2532f), s("protein", 0.3734f), s("vegetable", 0.3734f));
        food("undergardendelight:smoked_greater_dweller_hamleg", s("protein", 1.0f));
        food("undergardendelight:stuffed_gloomgourd", s("fruit", 0.1617f), s("protein", 0.2844f), s("vegetable", 0.5538f));
        food("undergardendelight:underbean_hotpot", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("undergardendelight:underbean_salad", s("protein", 0.4444f), s("vegetable", 0.5556f));
        food("undergardendelight:underdumplings", s("grain", 0.3333f), s("protein", 0.238f), s("vegetable", 0.4287f));
    }

    private static void vegandelight() {
        food("vegandelight:applesauce", s("fruit", 1.0f));
        food("vegandelight:cooked_smoked_tofish", s("protein", 0.8773f), s("vegetable", 0.1227f));
        food("vegandelight:cooked_smoked_tofu", s("dairy", 0.1317f), s("protein", 0.8683f));
        food("vegandelight:cooked_smoked_tofu_slices", s("protein", 1.0f));
        food("vegandelight:cooked_tofish", s("protein", 0.8159f), s("vegetable", 0.1841f));
        food("vegandelight:cooked_tofu", s("dairy", 0.1975f), s("protein", 0.8025f));
        food("vegandelight:cooked_tofu_slices", s("protein", 1.0f));
        food("vegandelight:minced_tofu", s("protein", 1.0f));
        food("vegandelight:pasta_with_tofuballs", s("grain", 0.5f), s("protein", 0.5f));
        food("vegandelight:roasted_tofu_chops", s("protein", 1.0f));
        food("vegandelight:silken_tofu", s("dairy", 0.2963f), s("protein", 0.7037f));
        food("vegandelight:smoked_tofish", s("protein", 0.8159f), s("vegetable", 0.1841f));
        food("vegandelight:smoked_tofish_roll", s("grain", 0.5096f), s("protein", 0.4904f));
        food("vegandelight:smoked_tofu", s("dairy", 0.1975f), s("protein", 0.8025f));
        food("vegandelight:smoked_tofu_slices", s("protein", 1.0f));
        food("vegandelight:soybean", s("protein", 1.0f));
        food("vegandelight:soymilk_bottle", s("dairy", 0.5556f), s("protein", 0.4444f));
        food("vegandelight:soymilk_bucket", s("dairy", 0.3333f), s("protein", 0.6667f));
        food("vegandelight:tofish", s("protein", 0.7239f), s("vegetable", 0.2761f));
        food("vegandelight:tofish_roll", s("grain", 0.4761f), s("protein", 0.4253f), s("vegetable", 0.0987f));
        food("vegandelight:tofish_slices", s("protein", 1.0f));
        food("vegandelight:tofu", s("dairy", 0.2963f), s("protein", 0.7037f));
        food("vegandelight:tofu_burger", s("grain", 0.3333f), s("protein", 0.6667f));
        food("vegandelight:tofu_patty", s("protein", 1.0f));
        food("vegandelight:tofu_sandwich", s("grain", 0.5f), s("protein", 0.5f));
        food("vegandelight:tofu_slices", s("protein", 1.0f));
    }

    private static void veggiesdelight() {
        food("veggiesdelight:baked_sweet_potato", s("vegetable", 1.0f));
        food("veggiesdelight:beetroot_brownie", s("grain", 0.5f), s("vegetable", 0.5f));
        food("veggiesdelight:beetroot_brownie_tray", s("grain", 0.5f), s("vegetable", 0.5f));
        food("veggiesdelight:bellpepper", s("vegetable", 1.0f));
        food("veggiesdelight:broccoli", s("vegetable", 1.0f));
        food("veggiesdelight:broccoli_salad", s("vegetable", 1.0f));
        food("veggiesdelight:broccoli_soup", s("dairy", 0.1208f), s("fruit", 0.0863f), s("vegetable", 0.7929f));
        food("veggiesdelight:cacciatore", s("protein", 0.4256f), s("vegetable", 0.5744f));
        food("veggiesdelight:carrot_cake", s("grain", 0.5f), s("vegetable", 0.5f));
        food("veggiesdelight:carrot_cake_slice", s("grain", 0.5f), s("vegetable", 0.5f));
        food("veggiesdelight:carrot_juice", s("vegetable", 1.0f));
        food("veggiesdelight:cauliflower", s("vegetable", 1.0f));
        food("veggiesdelight:cauliflower_bread", s("grain", 0.3756f), s("vegetable", 0.6244f));
        food("veggiesdelight:cauliflower_floret", s("vegetable", 1.0f));
        food("veggiesdelight:cauliflower_kuku", s("dairy", 0.0874f), s("vegetable", 0.9126f));
        food("veggiesdelight:cauliflower_soup", s("dairy", 0.1289f), s("vegetable", 0.8711f));
        food("veggiesdelight:cesar_salad", s("grain", 0.167f), s("vegetable", 0.833f));
        food("veggiesdelight:chicken_fajitas_wrap", s("grain", 0.3132f), s("protein", 0.368f), s("vegetable", 0.3188f));
        food("veggiesdelight:cooked_vegetarian_patty", s("protein", 0.6518f), s("vegetable", 0.3482f));
        food("veggiesdelight:dandelion_and_eggs", s("protein", 0.8267f), s("vegetable", 0.1733f));
        food("veggiesdelight:dandelion_juice", s("fruit", 0.3333f), s("vegetable", 0.6667f));
        food("veggiesdelight:dandelion_leaf", s("vegetable", 1.0f));
        food("veggiesdelight:fermented_garlic_honey", s("fruit", 0.3643f), s("vegetable", 0.6357f));
        food("veggiesdelight:fish_and_chips", s("protein", 0.6394f), s("vegetable", 0.3606f));
        food("veggiesdelight:garlic", s("vegetable", 1.0f));
        food("veggiesdelight:garlic_baked_cod", s("protein", 0.3572f), s("vegetable", 0.6428f));
        food("veggiesdelight:garlic_bread", s("grain", 0.2986f), s("vegetable", 0.7014f));
        food("veggiesdelight:garlic_chicken_stew", s("dairy", 0.1184f), s("protein", 0.498f), s("vegetable", 0.3837f));
        food("veggiesdelight:garlic_clove", s("vegetable", 1.0f));
        food("veggiesdelight:garlic_rice_with_cauliflower", s("grain", 0.4107f), s("vegetable", 0.5893f));
        food("veggiesdelight:garlic_stuffed_mushrooms", s("protein", 0.1916f), s("vegetable", 0.8084f));
        food("veggiesdelight:lasagna_pan", s("grain", 0.6685f), s("vegetable", 0.3315f));
        food("veggiesdelight:mashed_potatoes", s("dairy", 0.1321f), s("fruit", 0.0944f), s("vegetable", 0.7735f));
        food("veggiesdelight:mhadjeb", s("grain", 0.3642f), s("protein", 0.2571f), s("vegetable", 0.3788f));
        food("veggiesdelight:pasta_with_broccoli", s("dairy", 0.1201f), s("grain", 0.2843f), s("protein", 0.1624f), s("vegetable", 0.4331f));
        food("veggiesdelight:potato_noodle", s("grain", 0.1667f), s("vegetable", 0.8333f));
        food("veggiesdelight:potato_noodles", s("grain", 0.2778f), s("vegetable", 0.7222f));
        food("veggiesdelight:raw_vegetarian_patty", s("grain", 0.1095f), s("protein", 0.4063f), s("vegetable", 0.4842f));
        food("veggiesdelight:rice_and_vegetables", s("grain", 0.2983f), s("vegetable", 0.7017f));
        food("veggiesdelight:roasted_cauliflower_floret", s("vegetable", 1.0f));
        food("veggiesdelight:roasted_garlic_clove", s("vegetable", 1.0f));
        food("veggiesdelight:roasted_vegetables", s("vegetable", 1.0f));
        food("veggiesdelight:roasted_zucchini", s("vegetable", 1.0f));
        food("veggiesdelight:shakshouka", s("protein", 0.3462f), s("vegetable", 0.6538f));
        food("veggiesdelight:smoked_bellpepper", s("vegetable", 1.0f));
        food("veggiesdelight:steak_and_broccoli", s("grain", 0.2409f), s("protein", 0.4449f), s("vegetable", 0.3142f));
        food("veggiesdelight:stuffed_bellpepper", s("vegetable", 1.0f));
        food("veggiesdelight:stuffed_zucchinis", s("vegetable", 1.0f));
        food("veggiesdelight:sweet_potato", s("vegetable", 1.0f));
        food("veggiesdelight:sweet_potato_cupcake", s("dairy", 0.1358f), s("grain", 0.2706f), s("protein", 0.2897f), s("vegetable", 0.304f));
        food("veggiesdelight:sweet_potato_dough", s("grain", 0.3421f), s("protein", 0.1898f), s("vegetable", 0.468f));
        food("veggiesdelight:sweet_potato_pancakes", s("dairy", 0.0918f), s("fruit", 0.3804f), s("grain", 0.2499f), s("vegetable", 0.2779f));
        food("veggiesdelight:sweet_potato_pie", s("grain", 0.5f), s("vegetable", 0.5f));
        food("veggiesdelight:sweet_potato_pie_slice", s("grain", 0.5f), s("vegetable", 0.5f));
        food("veggiesdelight:turnip", s("vegetable", 1.0f));
        food("veggiesdelight:turnip_beef_stew", s("protein", 0.3889f), s("vegetable", 0.6111f));
        food("veggiesdelight:turnip_cake", s("grain", 0.3851f), s("vegetable", 0.6149f));
        food("veggiesdelight:turnip_mutton_skewer", s("protein", 0.5609f), s("vegetable", 0.4391f));
        food("veggiesdelight:turnip_salad", s("vegetable", 1.0f));
        food("veggiesdelight:turnip_water", s("vegetable", 1.0f));
        food("veggiesdelight:vegan_pizza", s("dairy", 0.3333f), s("grain", 0.6667f));
        food("veggiesdelight:vegan_pizza_slice", s("dairy", 0.3333f), s("grain", 0.6667f));
        food("veggiesdelight:vegetables_wrap", s("grain", 0.6558f), s("vegetable", 0.3442f));
        food("veggiesdelight:vegetarian_burger", s("grain", 0.2476f), s("protein", 0.3853f), s("vegetable", 0.3671f));
        food("veggiesdelight:zucchini", s("vegetable", 1.0f));
        food("veggiesdelight:zucchini_quiche", s("dairy", 0.2f), s("protein", 0.4f), s("vegetable", 0.4f));
        food("veggiesdelight:zucchini_quiche_slice", s("dairy", 0.2f), s("protein", 0.4f), s("vegetable", 0.4f));
        food("veggiesdelight:zucchini_sandwich", s("grain", 0.3313f), s("vegetable", 0.6687f));
        food("veggiesdelight:zucchini_slice", s("vegetable", 1.0f));
    }
}
