package com.breakinblocks.nutritional.datagen.builtin;

import static com.breakinblocks.nutritional.datagen.builtin.ModCompatFoods.food;
import static com.breakinblocks.nutritional.datagen.builtin.ModCompatFoods.s;

final class CompatCroptopia {

    private CompatCroptopia() {}

    static void register() {
        croptopia1();
        croptopia2();
        croptopia3();
    }

    private static void croptopia1() {
        food("croptopia:ajvar", s("fruit", 0.1332f), s("vegetable", 0.8668f));
        food("croptopia:ajvar_toast", s("grain", 0.6976f), s("vegetable", 0.3024f));
        food("croptopia:almond", s("protein", 1.0f));
        food("croptopia:almond_brittle", s("dairy", 0.3262f), s("protein", 0.6738f));
        food("croptopia:anchovy", s("protein", 1.0f));
        food("croptopia:anchovy_pizza", s("dairy", 0.1794f), s("grain", 0.29f), s("protein", 0.3692f), s("vegetable", 0.1615f));
        food("croptopia:apple_juice", s("fruit", 1.0f));
        food("croptopia:apple_pie", s("fruit", 0.3904f), s("grain", 0.4481f), s("protein", 0.1615f));
        food("croptopia:apricot", s("fruit", 1.0f));
        food("croptopia:apricot_jam", s("fruit", 1.0f));
        food("croptopia:artichoke", s("vegetable", 1.0f));
        food("croptopia:artichoke_dip", s("dairy", 0.2067f), s("protein", 0.1452f), s("vegetable", 0.6481f));
        food("croptopia:asparagus", s("vegetable", 1.0f));
        food("croptopia:avocado", s("fruit", 1.0f));
        food("croptopia:avocado_toast", s("fruit", 0.5f), s("grain", 0.5f));
        food("croptopia:bacon", s("protein", 1.0f));
        food("croptopia:baked_beans", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("croptopia:baked_crepes", s("dairy", 0.1645f), s("grain", 0.4154f), s("protein", 0.288f), s("vegetable", 0.1322f));
        food("croptopia:baked_sweet_potato", s("vegetable", 1.0f));
        food("croptopia:baked_yam", s("vegetable", 1.0f));
        food("croptopia:banana", s("fruit", 1.0f));
        food("croptopia:banana_cream_pie", s("dairy", 0.2516f), s("fruit", 0.4385f), s("grain", 0.1111f), s("protein", 0.1988f));
        food("croptopia:banana_nut_bread", s("fruit", 0.4528f), s("grain", 0.2642f), s("protein", 0.283f));
        food("croptopia:banana_smoothie", s("dairy", 0.3115f), s("fruit", 0.6885f));
        food("croptopia:barley", s("grain", 1.0f));
        food("croptopia:basil", s("vegetable", 1.0f));
        food("croptopia:beef_jerky", s("protein", 1.0f));
        food("croptopia:beef_stew", s("grain", 0.0975f), s("protein", 0.3791f), s("vegetable", 0.5235f));
        food("croptopia:beef_stir_fry", s("fruit", 0.1041f), s("protein", 0.4538f), s("vegetable", 0.4421f));
        food("croptopia:beef_wellington", s("grain", 0.1879f), s("protein", 0.4896f), s("vegetable", 0.3225f));
        food("croptopia:beer", s("grain", 1.0f));
        food("croptopia:beetroot_salad", s("dairy", 0.1381f), s("fruit", 0.1269f), s("vegetable", 0.735f));
        food("croptopia:bellpepper", s("vegetable", 1.0f));
        food("croptopia:blackbean", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("croptopia:blackberry", s("fruit", 1.0f));
        food("croptopia:blackberry_jam", s("fruit", 1.0f));
        food("croptopia:blt", s("grain", 0.3314f), s("protein", 0.302f), s("vegetable", 0.3666f));
        food("croptopia:blueberry", s("fruit", 1.0f));
        food("croptopia:blueberry_jam", s("fruit", 1.0f));
        food("croptopia:borscht", s("vegetable", 1.0f));
        food("croptopia:broccoli", s("vegetable", 1.0f));
        food("croptopia:brownies", s("dairy", 0.2176f), s("fruit", 0.1407f), s("grain", 0.4573f), s("protein", 0.1845f));
        food("croptopia:burrito", s("grain", 0.6795f), s("protein", 0.0964f), s("vegetable", 0.2241f));
        food("croptopia:butter", s("dairy", 0.8889f), s("protein", 0.1111f));
        food("croptopia:buttered_green_beans", s("dairy", 0.3051f), s("protein", 0.1407f), s("vegetable", 0.5541f));
        food("croptopia:buttered_toast", s("dairy", 0.5138f), s("grain", 0.4862f));
        food("croptopia:cabbage", s("vegetable", 1.0f));
        food("croptopia:cabbage_roll", s("grain", 0.257f), s("protein", 0.216f), s("vegetable", 0.5269f));
        food("croptopia:caesar_salad", s("fruit", 0.1667f), s("grain", 0.1667f), s("vegetable", 0.6667f));
        food("croptopia:calamari", s("protein", 1.0f));
        food("croptopia:candied_kumquats", s("fruit", 1.0f));
        food("croptopia:candied_nuts", s("protein", 1.0f));
        food("croptopia:candy_corn", s("fruit", 0.0833f), s("grain", 0.3056f), s("vegetable", 0.6111f));
        food("croptopia:cantaloupe", s("fruit", 1.0f));
        food("croptopia:caramel", s("fruit", 1.0f));
        food("croptopia:carnitas", s("grain", 0.1965f), s("protein", 0.5059f), s("vegetable", 0.2975f));
        food("croptopia:cashew", s("protein", 1.0f));
        food("croptopia:cashew_chicken", s("protein", 0.7489f), s("vegetable", 0.2511f));
        food("croptopia:cauliflower", s("vegetable", 1.0f));
        food("croptopia:celery", s("vegetable", 1.0f));
        food("croptopia:cheese", s("dairy", 0.8889f), s("protein", 0.1111f));
        food("croptopia:cheese_cake", s("dairy", 0.5f), s("grain", 0.5f));
        food("croptopia:cheese_pizza", s("dairy", 0.3807f), s("grain", 0.3155f), s("protein", 0.1504f), s("vegetable", 0.1534f));
        food("croptopia:cheeseburger", s("dairy", 0.2032f), s("grain", 0.3156f), s("protein", 0.4812f));
        food("croptopia:cheesy_asparagus", s("dairy", 0.1204f), s("fruit", 0.1674f), s("vegetable", 0.7122f));
        food("croptopia:cherry", s("fruit", 1.0f));
        food("croptopia:cherry_jam", s("fruit", 1.0f));
        food("croptopia:cherry_pie", s("fruit", 0.3432f), s("grain", 0.4781f), s("protein", 0.1787f));
        food("croptopia:chicken_and_dumplings", s("grain", 0.3993f), s("protein", 0.3681f), s("vegetable", 0.2326f));
        food("croptopia:chicken_and_noodles", s("fruit", 0.1724f), s("grain", 0.3188f), s("protein", 0.316f), s("vegetable", 0.1928f));
        food("croptopia:chicken_and_rice", s("fruit", 0.1638f), s("grain", 0.3305f), s("protein", 0.3418f), s("vegetable", 0.1638f));
        food("croptopia:chile_pepper", s("vegetable", 1.0f));
        food("croptopia:chili_relleno", s("fruit", 0.1667f), s("grain", 0.1481f), s("protein", 0.1667f), s("vegetable", 0.5185f));
        food("croptopia:chimichanga", s("grain", 0.6895f), s("protein", 0.1988f), s("vegetable", 0.1117f));
        food("croptopia:chocolate", s("dairy", 0.3942f), s("fruit", 0.6058f));
        food("croptopia:chocolate_ice_cream", s("dairy", 0.5244f), s("fruit", 0.2894f), s("protein", 0.1862f));
        food("croptopia:chocolate_milkshake", s("dairy", 0.5961f), s("fruit", 0.3228f), s("protein", 0.0811f));
        food("croptopia:churros", s("dairy", 0.2127f), s("fruit", 0.2283f), s("grain", 0.5589f));
        food("croptopia:cinnamon", s("fruit", 1.0f));
        food("croptopia:cinnamon_roll", s("dairy", 0.2765f), s("fruit", 0.1413f), s("grain", 0.4392f), s("protein", 0.143f));
        food("croptopia:clam", s("protein", 1.0f));
        food("croptopia:coconut", s("fruit", 1.0f));
        food("croptopia:coffee", s("fruit", 0.5f), s("protein", 0.3333f), s("vegetable", 0.1667f));
        food("croptopia:coffee_beans", s("fruit", 0.25f), s("protein", 0.5f), s("vegetable", 0.25f));
        food("croptopia:cooked_anchovy", s("protein", 1.0f));
        food("croptopia:cooked_bacon", s("protein", 1.0f));
        food("croptopia:cooked_calamari", s("protein", 1.0f));
        food("croptopia:cooked_ravager_meat", s("protein", 1.0f));
        food("croptopia:cooked_shrimp", s("protein", 1.0f));
        food("croptopia:cooked_tuna", s("protein", 1.0f));
        food("croptopia:corn", s("grain", 0.3333f), s("vegetable", 0.6667f));
        food("croptopia:corn_bread", s("grain", 0.3889f), s("vegetable", 0.6111f));
        food("croptopia:cornish_pasty", s("grain", 0.2583f), s("protein", 0.2309f), s("vegetable", 0.5108f));
        food("croptopia:crab", s("protein", 1.0f));
        food("croptopia:crab_legs", s("dairy", 0.142f), s("protein", 0.612f), s("vegetable", 0.2461f));
        food("croptopia:cranberry", s("fruit", 1.0f));
        food("croptopia:cranberry_juice", s("fruit", 1.0f));
        food("croptopia:crema", s("dairy", 0.6656f), s("fruit", 0.3344f));
        food("croptopia:croque_madame", s("dairy", 0.2321f), s("grain", 0.3337f), s("protein", 0.4341f));
        food("croptopia:croque_monsieur", s("dairy", 0.2583f), s("grain", 0.3654f), s("protein", 0.3763f));
        food("croptopia:cucumber", s("vegetable", 1.0f));
        food("croptopia:cucumber_salad", s("vegetable", 1.0f));
        food("croptopia:currant", s("fruit", 1.0f));
        food("croptopia:date", s("fruit", 1.0f));
        food("croptopia:dauphine_potatoes", s("dairy", 0.3216f), s("fruit", 0.1652f), s("grain", 0.1299f), s("vegetable", 0.3833f));
        food("croptopia:deep_fried_shrimp", s("grain", 0.1665f), s("protein", 0.8335f));
        food("croptopia:dough", s("grain", 1.0f));
        food("croptopia:doughnut", s("dairy", 0.2183f), s("grain", 0.7817f));
        food("croptopia:dragon_egg_omelette", s("dairy", 0.2155f), s("protein", 0.4848f), s("vegetable", 0.2997f));
        food("croptopia:dragonfruit", s("fruit", 1.0f));
    }

    private static void croptopia2() {
        food("croptopia:egg_roll", s("grain", 0.3273f), s("protein", 0.4993f), s("vegetable", 0.1735f));
        food("croptopia:eggplant", s("vegetable", 1.0f));
        food("croptopia:eggplant_parmesan", s("dairy", 0.2733f), s("fruit", 0.098f), s("grain", 0.1365f), s("protein", 0.1296f), s("vegetable", 0.3626f));
        food("croptopia:elderberry", s("fruit", 1.0f));
        food("croptopia:elderberry_jam", s("fruit", 1.0f));
        food("croptopia:enchilada", s("dairy", 0.0977f), s("grain", 0.3561f), s("protein", 0.3808f), s("vegetable", 0.1653f));
        food("croptopia:eton_mess", s("dairy", 0.2554f), s("fruit", 0.4779f), s("protein", 0.2667f));
        food("croptopia:fajitas", s("dairy", 0.0912f), s("grain", 0.1333f), s("protein", 0.3332f), s("vegetable", 0.4423f));
        food("croptopia:fig", s("fruit", 1.0f));
        food("croptopia:figgy_pudding", s("dairy", 0.3332f), s("fruit", 0.3891f), s("grain", 0.1111f), s("protein", 0.1667f));
        food("croptopia:fish_and_chips", s("grain", 0.1417f), s("protein", 0.3531f), s("vegetable", 0.5051f));
        food("croptopia:flour", s("grain", 0.8889f), s("vegetable", 0.1111f));
        food("croptopia:french_fries", s("fruit", 0.3905f), s("vegetable", 0.6095f));
        food("croptopia:fried_calamari", s("fruit", 0.2667f), s("grain", 0.1049f), s("protein", 0.4722f), s("vegetable", 0.1562f));
        food("croptopia:fried_chicken", s("fruit", 0.1638f), s("grain", 0.1289f), s("protein", 0.5153f), s("vegetable", 0.192f));
        food("croptopia:fried_frog_legs", s("protein", 1.0f));
        food("croptopia:frog_legs", s("protein", 1.0f));
        food("croptopia:fruit_cake", s("fruit", 0.4696f), s("grain", 0.1735f), s("protein", 0.3568f));
        food("croptopia:fruit_salad", s("fruit", 0.8333f), s("vegetable", 0.1667f));
        food("croptopia:fruit_smoothie", s("dairy", 0.1622f), s("fruit", 0.8378f));
        food("croptopia:garlic", s("vegetable", 1.0f));
        food("croptopia:ginger", s("vegetable", 1.0f));
        food("croptopia:glowing_calamari", s("protein", 1.0f));
        food("croptopia:goulash", s("protein", 0.5446f), s("vegetable", 0.4554f));
        food("croptopia:grape", s("fruit", 1.0f));
        food("croptopia:grape_jam", s("fruit", 1.0f));
        food("croptopia:grape_juice", s("fruit", 1.0f));
        food("croptopia:grapefruit", s("fruit", 1.0f));
        food("croptopia:greenbean", s("protein", 0.3333f), s("vegetable", 0.6667f));
        food("croptopia:greenonion", s("vegetable", 1.0f));
        food("croptopia:grilled_cheese", s("dairy", 0.5042f), s("grain", 0.3312f), s("protein", 0.1646f));
        food("croptopia:grilled_eggplant", s("fruit", 0.1342f), s("vegetable", 0.8658f));
        food("croptopia:grilled_oysters", s("dairy", 0.0938f), s("fruit", 0.1304f), s("protein", 0.6601f), s("vegetable", 0.1156f));
        food("croptopia:ground_pork", s("protein", 1.0f));
        food("croptopia:ham_sandwich", s("dairy", 0.0998f), s("grain", 0.36f), s("protein", 0.5402f));
        food("croptopia:hamburger", s("grain", 0.4423f), s("protein", 0.5577f));
        food("croptopia:hashed_brown", s("fruit", 0.3573f), s("vegetable", 0.6427f));
        food("croptopia:honeydew", s("fruit", 1.0f));
        food("croptopia:hops", s("grain", 1.0f));
        food("croptopia:horchata", s("dairy", 0.2222f), s("fruit", 0.3333f), s("grain", 0.2778f), s("protein", 0.1667f));
        food("croptopia:kale", s("vegetable", 1.0f));
        food("croptopia:kale_chips", s("fruit", 0.3182f), s("vegetable", 0.6818f));
        food("croptopia:kale_smoothie", s("dairy", 0.2191f), s("fruit", 0.183f), s("vegetable", 0.5978f));
        food("croptopia:kiwi", s("fruit", 1.0f));
        food("croptopia:kiwi_sorbet", s("fruit", 1.0f));
        food("croptopia:kumquat", s("fruit", 1.0f));
        food("croptopia:leafy_salad", s("vegetable", 1.0f));
        food("croptopia:leek", s("vegetable", 1.0f));
        food("croptopia:leek_soup", s("dairy", 0.2199f), s("protein", 0.1106f), s("vegetable", 0.6695f));
        food("croptopia:lemon", s("fruit", 1.0f));
        food("croptopia:lemon_chicken", s("fruit", 0.3453f), s("protein", 0.3214f), s("vegetable", 0.3333f));
        food("croptopia:lemon_coconut_bar", s("dairy", 0.142f), s("fruit", 0.6017f), s("grain", 0.1026f), s("protein", 0.1536f));
        food("croptopia:lemonade", s("fruit", 1.0f));
        food("croptopia:lettuce", s("vegetable", 1.0f));
        food("croptopia:lime", s("fruit", 1.0f));
        food("croptopia:limeade", s("fruit", 1.0f));
        food("croptopia:macaron", s("grain", 0.3333f), s("protein", 0.6667f));
        food("croptopia:mango", s("fruit", 1.0f));
        food("croptopia:mango_ice_cream", s("dairy", 0.3528f), s("fruit", 0.3837f), s("protein", 0.2635f));
        food("croptopia:mashed_potatoes", s("dairy", 0.3186f), s("vegetable", 0.6814f));
        food("croptopia:mead", s("fruit", 1.0f));
        food("croptopia:melon_juice", s("fruit", 1.0f));
        food("croptopia:meringue", s("fruit", 0.1667f), s("grain", 0.1667f), s("protein", 0.6667f));
        food("croptopia:milk_bottle", s("dairy", 1.0f));
        food("croptopia:molasses", s("fruit", 1.0f));
        food("croptopia:mustard", s("vegetable", 1.0f));
        food("croptopia:nectarine", s("fruit", 1.0f));
        food("croptopia:nether_star_cake", s("grain", 1.0f));
        food("croptopia:nether_wart_stew", s("grain", 0.2622f), s("protein", 0.1805f), s("vegetable", 0.5573f));
        food("croptopia:noodle", s("grain", 0.8822f), s("vegetable", 0.1178f));
        food("croptopia:nougat", s("fruit", 0.1667f), s("protein", 0.8333f));
        food("croptopia:nutmeg", s("protein", 1.0f));
        food("croptopia:nutty_cookie", s("grain", 0.5443f), s("protein", 0.4557f));
        food("croptopia:oat", s("grain", 1.0f));
        food("croptopia:oatmeal", s("dairy", 0.3105f), s("grain", 0.5686f), s("protein", 0.1209f));
        food("croptopia:olive", s("fruit", 1.0f));
        food("croptopia:onion", s("vegetable", 1.0f));
        food("croptopia:onion_rings", s("fruit", 0.2222f), s("grain", 0.1975f), s("vegetable", 0.5802f));
        food("croptopia:orange", s("fruit", 1.0f));
        food("croptopia:orange_juice", s("fruit", 1.0f));
        food("croptopia:oyster", s("protein", 1.0f));
        food("croptopia:peach", s("fruit", 1.0f));
        food("croptopia:peach_jam", s("fruit", 1.0f));
        food("croptopia:peanut", s("protein", 1.0f));
        food("croptopia:peanut_butter", s("dairy", 0.1667f), s("protein", 0.8333f));
        food("croptopia:peanut_butter_and_jam", s("dairy", 0.1421f), s("fruit", 0.2973f), s("grain", 0.2595f), s("protein", 0.3011f));
        food("croptopia:peanut_butter_with_celery", s("dairy", 0.1641f), s("protein", 0.3762f), s("vegetable", 0.4596f));
        food("croptopia:pear", s("fruit", 1.0f));
        food("croptopia:pecan", s("protein", 1.0f));
        food("croptopia:pecan_ice_cream", s("dairy", 0.3528f), s("protein", 0.6472f));
        food("croptopia:pecan_pie", s("grain", 0.4781f), s("protein", 0.5219f));
        food("croptopia:pepper", s("vegetable", 1.0f));
        food("croptopia:pepperoni", s("protein", 0.7003f), s("vegetable", 0.2997f));
        food("croptopia:persimmon", s("fruit", 1.0f));
        food("croptopia:pineapple", s("fruit", 1.0f));
        food("croptopia:pineapple_juice", s("fruit", 1.0f));
        food("croptopia:pineapple_pepperoni_pizza", s("dairy", 0.1178f), s("fruit", 0.2903f), s("grain", 0.1928f), s("protein", 0.2515f), s("vegetable", 0.1477f));
        food("croptopia:pizza", s("dairy", 0.2584f), s("grain", 0.427f), s("protein", 0.1035f), s("vegetable", 0.2111f));
        food("croptopia:plum", s("fruit", 1.0f));
        food("croptopia:popcorn", s("grain", 0.4444f), s("vegetable", 0.5556f));
        food("croptopia:pork_and_beans", s("protein", 0.789f), s("vegetable", 0.211f));
        food("croptopia:pork_jerky", s("protein", 1.0f));
        food("croptopia:potato_chips", s("fruit", 0.3905f), s("vegetable", 0.6095f));
        food("croptopia:potato_soup", s("grain", 0.1415f), s("protein", 0.254f), s("vegetable", 0.6046f));
        food("croptopia:protein_bar", s("dairy", 0.1565f), s("fruit", 0.2196f), s("grain", 0.1111f), s("protein", 0.5128f));
        food("croptopia:pumpkin_soup", s("vegetable", 1.0f));
        food("croptopia:pumpkin_spice_latte", s("dairy", 0.2978f), s("fruit", 0.1209f), s("protein", 0.1134f), s("vegetable", 0.4679f));
        food("croptopia:quesadilla", s("dairy", 0.1928f), s("fruit", 0.1074f), s("grain", 0.5307f), s("protein", 0.1691f));
        food("croptopia:quiche", s("dairy", 0.2241f), s("grain", 0.1036f), s("protein", 0.3876f), s("vegetable", 0.2847f));
        food("croptopia:radish", s("vegetable", 1.0f));
    }

    private static void croptopia3() {
        food("croptopia:raisin_oatmeal_cookie", s("fruit", 0.45f), s("grain", 0.55f));
        food("croptopia:raisins", s("fruit", 1.0f));
        food("croptopia:raspberry", s("fruit", 1.0f));
        food("croptopia:raspberry_jam", s("fruit", 1.0f));
        food("croptopia:ratatouille", s("fruit", 0.0818f), s("vegetable", 0.9182f));
        food("croptopia:ravioli", s("dairy", 0.2234f), s("grain", 0.6196f), s("protein", 0.157f));
        food("croptopia:raw_ravager_meat", s("protein", 1.0f));
        food("croptopia:refried_beans", s("dairy", 0.1135f), s("protein", 0.5124f), s("vegetable", 0.3741f));
        food("croptopia:rhubarb", s("fruit", 1.0f));
        food("croptopia:rhubarb_crisp", s("dairy", 0.1868f), s("fruit", 0.6783f), s("grain", 0.1349f));
        food("croptopia:rhubarb_pie", s("fruit", 0.3295f), s("grain", 0.4868f), s("protein", 0.1837f));
        food("croptopia:rice", s("grain", 1.0f));
        food("croptopia:roasted_asparagus", s("fruit", 0.1674f), s("vegetable", 0.8326f));
        food("croptopia:roasted_nuts", s("protein", 1.0f));
        food("croptopia:roasted_pumpkin_seeds", s("vegetable", 1.0f));
        food("croptopia:roasted_radishes", s("fruit", 0.1763f), s("vegetable", 0.8237f));
        food("croptopia:roasted_squash", s("fruit", 0.1715f), s("vegetable", 0.8285f));
        food("croptopia:roasted_sunflower_seeds", s("protein", 0.3333f), s("vegetable", 0.6667f));
        food("croptopia:roasted_turnips", s("fruit", 0.1749f), s("vegetable", 0.8251f));
        food("croptopia:roe", s("protein", 1.0f));
        food("croptopia:rum", s("fruit", 1.0f));
        food("croptopia:rum_raisin_ice_cream", s("dairy", 0.2824f), s("fruit", 0.5538f), s("protein", 0.1638f));
        food("croptopia:rutabaga", s("vegetable", 1.0f));
        food("croptopia:saguaro", s("fruit", 1.0f));
        food("croptopia:saguaro_juice", s("fruit", 1.0f));
        food("croptopia:salsa", s("fruit", 0.1616f), s("vegetable", 0.8384f));
        food("croptopia:saucy_chips", s("fruit", 0.1442f), s("vegetable", 0.8558f));
        food("croptopia:sausage", s("protein", 0.6667f), s("vegetable", 0.3333f));
        food("croptopia:scones", s("fruit", 0.3432f), s("grain", 0.4781f), s("protein", 0.1787f));
        food("croptopia:scrambled_eggs", s("dairy", 0.2155f), s("protein", 0.7845f));
        food("croptopia:sea_lettuce", s("vegetable", 1.0f));
        food("croptopia:shepherds_pie", s("grain", 0.3669f), s("protein", 0.111f), s("vegetable", 0.5221f));
        food("croptopia:shrimp", s("protein", 1.0f));
        food("croptopia:snicker_doodle", s("fruit", 0.3589f), s("grain", 0.6411f));
        food("croptopia:soy_milk", s("dairy", 0.3333f), s("protein", 0.6667f));
        food("croptopia:soybean", s("protein", 1.0f));
        food("croptopia:spaghetti_squash", s("fruit", 0.2222f), s("grain", 0.1667f), s("vegetable", 0.6111f));
        food("croptopia:spinach", s("vegetable", 1.0f));
        food("croptopia:squash", s("vegetable", 1.0f));
        food("croptopia:starfruit", s("fruit", 1.0f));
        food("croptopia:steamed_broccoli", s("vegetable", 1.0f));
        food("croptopia:steamed_clams", s("dairy", 0.142f), s("protein", 0.612f), s("vegetable", 0.2461f));
        food("croptopia:steamed_crab", s("protein", 1.0f));
        food("croptopia:steamed_green_beans", s("protein", 0.3333f), s("vegetable", 0.6667f));
        food("croptopia:steamed_rice", s("grain", 1.0f));
        food("croptopia:sticky_toffee_pudding", s("dairy", 0.4461f), s("fruit", 0.2979f), s("grain", 0.1111f), s("protein", 0.145f));
        food("croptopia:stir_fry", s("fruit", 0.1072f), s("protein", 0.1111f), s("vegetable", 0.7817f));
        food("croptopia:strawberry", s("fruit", 1.0f));
        food("croptopia:strawberry_ice_cream", s("dairy", 0.3528f), s("fruit", 0.3837f), s("protein", 0.2635f));
        food("croptopia:strawberry_jam", s("fruit", 1.0f));
        food("croptopia:strawberry_smoothie", s("dairy", 0.3115f), s("fruit", 0.6885f));
        food("croptopia:stuffed_artichoke", s("fruit", 0.2237f), s("grain", 0.1559f), s("vegetable", 0.6204f));
        food("croptopia:stuffed_poblanos", s("dairy", 0.2242f), s("grain", 0.1385f), s("protein", 0.2075f), s("vegetable", 0.4299f));
        food("croptopia:sunny_side_eggs", s("protein", 1.0f));
        food("croptopia:supreme_pizza", s("dairy", 0.1865f), s("fruit", 0.1048f), s("grain", 0.327f), s("protein", 0.1651f), s("vegetable", 0.2167f));
        food("croptopia:sushi", s("grain", 0.4778f), s("protein", 0.3415f), s("vegetable", 0.1807f));
        food("croptopia:sweet_crepes", s("dairy", 0.1445f), s("fruit", 0.1684f), s("grain", 0.4755f), s("protein", 0.2116f));
        food("croptopia:sweet_potato_fries", s("fruit", 0.3333f), s("vegetable", 0.6667f));
        food("croptopia:sweetpotato", s("vegetable", 1.0f));
        food("croptopia:taco", s("dairy", 0.1515f), s("grain", 0.3452f), s("protein", 0.1796f), s("vegetable", 0.3237f));
        food("croptopia:tamales", s("grain", 0.3569f), s("protein", 0.2894f), s("vegetable", 0.3537f));
        food("croptopia:tea", s("fruit", 1.0f));
        food("croptopia:the_big_breakfast", s("grain", 0.1916f), s("protein", 0.5195f), s("vegetable", 0.2889f));
        food("croptopia:toast", s("grain", 1.0f));
        food("croptopia:toast_sandwich", s("dairy", 0.0876f), s("grain", 0.9124f));
        food("croptopia:toast_with_jam", s("fruit", 0.5f), s("grain", 0.5f));
        food("croptopia:tofu", s("protein", 1.0f));
        food("croptopia:tofu_and_dumplings", s("grain", 0.3528f), s("protein", 0.461f), s("vegetable", 0.1862f));
        food("croptopia:tofuburger", s("grain", 0.292f), s("protein", 0.4517f), s("vegetable", 0.2563f));
        food("croptopia:tomatillo", s("vegetable", 1.0f));
        food("croptopia:tomato", s("vegetable", 1.0f));
        food("croptopia:tomato_juice", s("vegetable", 1.0f));
        food("croptopia:tortilla", s("grain", 0.8822f), s("vegetable", 0.1178f));
        food("croptopia:tostada", s("grain", 0.3856f), s("protein", 0.1562f), s("vegetable", 0.4582f));
        food("croptopia:trail_mix", s("fruit", 0.3757f), s("protein", 0.6243f));
        food("croptopia:treacle_tart", s("fruit", 0.267f), s("grain", 0.733f));
        food("croptopia:tres_leche_cake", s("dairy", 0.1487f), s("fruit", 0.3129f), s("grain", 0.4157f), s("protein", 0.1226f));
        food("croptopia:trifle", s("dairy", 0.215f), s("fruit", 0.4283f), s("grain", 0.2396f), s("protein", 0.1172f));
        food("croptopia:tuna", s("protein", 1.0f));
        food("croptopia:tuna_roll", s("grain", 0.3518f), s("protein", 0.3518f), s("vegetable", 0.2965f));
        food("croptopia:tuna_sandwich", s("grain", 0.5f), s("protein", 0.5f));
        food("croptopia:turmeric", s("vegetable", 1.0f));
        food("croptopia:turnip", s("vegetable", 1.0f));
        food("croptopia:vanilla", s("fruit", 1.0f));
        food("croptopia:vanilla_ice_cream", s("dairy", 0.5195f), s("fruit", 0.217f), s("protein", 0.2635f));
        food("croptopia:veggie_salad", s("vegetable", 1.0f));
        food("croptopia:walnut", s("protein", 1.0f));
        food("croptopia:whipping_cream", s("dairy", 0.6656f), s("fruit", 0.3344f));
        food("croptopia:wine", s("fruit", 1.0f));
        food("croptopia:yam", s("vegetable", 1.0f));
        food("croptopia:yam_jam", s("dairy", 0.2964f), s("fruit", 0.3518f), s("vegetable", 0.3518f));
        food("croptopia:yoghurt", s("dairy", 0.6656f), s("fruit", 0.3344f));
        food("croptopia:zucchini", s("vegetable", 1.0f));
    }
}
